import type { ServiceCategory, IndustryInfo } from "@/lib/types";
import { RESEARCH_SERVICES } from "../research-services";
import { ENGINEERING_SERVICES } from "../engineering-services";
import { INDUSTRIES } from "../industries";

import researchFr from "./research.fr.json";
import researchAr from "./research.ar.json";
import engineeringFr from "./engineering.fr.json";
import engineeringAr from "./engineering.ar.json";
import industriesFr from "./industries.fr.json";
import industriesAr from "./industries.ar.json";

/**
 * Locale accessors for the big content constants. English is the source of
 * truth; per-locale override files (generated by scripts/i18n-content.ts) carry
 * ONLY the translated leaf strings keyed by entry id + dot-path. We deep-clone
 * the English entry and apply the override, so structural/non-translatable
 * fields (ids, hrefs, icons, codes, product names) always stay correct and any
 * untranslated path falls back to English automatically.
 */

type Overrides = Record<string, Record<string, string>>;

const RESEARCH_OVERRIDES: Record<string, Overrides> = {
  fr: researchFr as Overrides,
  ar: researchAr as Overrides,
};
const ENGINEERING_OVERRIDES: Record<string, Overrides> = {
  fr: engineeringFr as Overrides,
  ar: engineeringAr as Overrides,
};
const INDUSTRIES_OVERRIDES: Record<string, Overrides> = {
  fr: industriesFr as Overrides,
  ar: industriesAr as Overrides,
};

/** Set a dot-path (with numeric array indices) on a mutable clone. */
function setByPath(obj: Record<string, unknown>, path: string, value: string) {
  const parts = path.split(".");
  let cur: unknown = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur == null || typeof cur !== "object") return;
    cur = (cur as Record<string, unknown>)[parts[i]];
  }
  if (cur && typeof cur === "object") {
    (cur as Record<string, unknown>)[parts[parts.length - 1]] = value;
  }
}

function applyOverrides<T extends { id: string }>(
  items: readonly T[],
  overrides: Overrides | undefined,
): T[] {
  if (!overrides) return items as T[];
  return items.map((item) => {
    const ov = overrides[item.id];
    if (!ov) return item;
    const clone = structuredClone(item) as T;
    for (const [path, value] of Object.entries(ov)) {
      setByPath(clone as unknown as Record<string, unknown>, path, value);
    }
    return clone;
  });
}

const cache = new Map<string, unknown>();
function memo<T>(key: string, build: () => T): T {
  if (!cache.has(key)) cache.set(key, build());
  return cache.get(key) as T;
}

export function localizeResearchServices(locale: string): ServiceCategory[] {
  if (locale === "en") return RESEARCH_SERVICES as unknown as ServiceCategory[];
  return memo(`research:${locale}`, () =>
    applyOverrides(
      RESEARCH_SERVICES as unknown as ServiceCategory[],
      RESEARCH_OVERRIDES[locale],
    ),
  );
}

export function localizeEngineeringServices(locale: string): ServiceCategory[] {
  if (locale === "en") return ENGINEERING_SERVICES as unknown as ServiceCategory[];
  return memo(`engineering:${locale}`, () =>
    applyOverrides(
      ENGINEERING_SERVICES as unknown as ServiceCategory[],
      ENGINEERING_OVERRIDES[locale],
    ),
  );
}

export function localizeIndustries(locale: string): IndustryInfo[] {
  if (locale === "en") return INDUSTRIES as unknown as IndustryInfo[];
  return memo(`industries:${locale}`, () =>
    applyOverrides(
      INDUSTRIES as unknown as IndustryInfo[],
      INDUSTRIES_OVERRIDES[locale],
    ),
  );
}
