import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  PageBreak,
} from "docx";

import { sanitiseBodyDoc, type PMLike } from "@/lib/regwatch/templates/sanitise-body-doc";

/**
 * ProseMirror JSON → DOCX. Maps the locked v1 node set onto the `docx`
 * library's Document model. Output is a Buffer ready to upload to storage.
 *
 * Supported nodes:
 *   doc / paragraph / heading(1-3) / text(+ bold/italic/underline marks)
 *   bulletList / orderedList / listItem
 *   table / tableRow / tableCell / tableHeader
 *   horizontalRule (→ blank paragraph with bottom border)
 *   pageBreak (→ Paragraph child with native PageBreak run)
 */
export async function bodyDocToDocxBuffer(
  bodyDoc: unknown,
  meta: { title: string },
): Promise<Buffer> {
  const root = sanitiseBodyDoc(bodyDoc) as PMLike | null;
  const children: (Paragraph | Table)[] = [
    new Paragraph({
      text: meta.title,
      heading: HeadingLevel.TITLE,
    }),
  ];
  if (root && Array.isArray(root.content)) {
    for (const node of root.content) {
      const mapped = mapBlock(node as PMLike);
      if (Array.isArray(mapped)) children.push(...mapped);
      else if (mapped) children.push(mapped);
    }
  }
  const doc = new Document({
    creator: "intelle.io RegWatch",
    title: meta.title,
    description: "Generated by RegWatch internal documents",
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch in twips
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children,
      },
    ],
  });
  return await Packer.toBuffer(doc);
}

function mapBlock(node: PMLike): Paragraph | Table | (Paragraph | Table)[] | null {
  switch (node.type) {
    case "heading":
      return mapHeading(node);
    case "paragraph":
      return new Paragraph({ children: mapInline(node.content as PMLike[] | undefined) });
    case "bulletList":
      return mapList(node, false);
    case "orderedList":
      return mapList(node, true);
    case "table":
      return mapTable(node);
    case "horizontalRule":
      return new Paragraph({
        border: {
          bottom: {
            style: BorderStyle.SINGLE,
            size: 6,
            color: "888888",
            space: 1,
          },
        },
      });
    case "pageBreak":
      return new Paragraph({ children: [new PageBreak()] });
    case "blockquote":
      return mapBlockquote(node);
    case "codeBlock":
      return new Paragraph({
        children: mapInline(node.content as PMLike[] | undefined),
        style: "Code",
      });
    default:
      return null;
  }
}

function mapHeading(node: PMLike): Paragraph {
  const level = (node.attrs?.level as number | undefined) ?? 1;
  const heading =
    level === 1
      ? HeadingLevel.HEADING_1
      : level === 2
        ? HeadingLevel.HEADING_2
        : HeadingLevel.HEADING_3;
  return new Paragraph({
    heading,
    children: mapInline(node.content as PMLike[] | undefined),
  });
}

function mapInline(content: PMLike[] | undefined): TextRun[] {
  if (!content) return [];
  const runs: TextRun[] = [];
  for (const child of content) {
    if (child.type !== "text" || typeof child.text !== "string") continue;
    const marks = (child.marks as PMLike[] | undefined) ?? [];
    const flags = {
      bold: marks.some((m) => m.type === "bold"),
      italics: marks.some((m) => m.type === "italic"),
      underline: marks.some((m) => m.type === "underline") ? {} : undefined,
    };
    runs.push(
      new TextRun({
        text: child.text,
        bold: flags.bold,
        italics: flags.italics,
        underline: flags.underline,
      }),
    );
  }
  return runs;
}

function mapList(node: PMLike, ordered: boolean): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const items = (node.content as PMLike[] | undefined) ?? [];
  for (const item of items) {
    const itemChildren = (item.content as PMLike[] | undefined) ?? [];
    for (const child of itemChildren) {
      if (child.type !== "paragraph") {
        const mapped = mapBlock(child);
        if (mapped && !Array.isArray(mapped) && mapped instanceof Paragraph) {
          paragraphs.push(mapped);
        }
        continue;
      }
      paragraphs.push(
        new Paragraph({
          children: mapInline(child.content as PMLike[] | undefined),
          bullet: ordered ? undefined : { level: 0 },
          numbering: ordered
            ? { reference: "default-numbering", level: 0 }
            : undefined,
        }),
      );
    }
  }
  return paragraphs;
}

// US Letter content area = 8.5in page − 2 × 1in margins = 6.5in = 9360 twips.
// Without explicit column widths Word renders each cell at ~1 character wide
// and content stacks vertically. We compute widths from the first row's cell
// count and apply them to both the Table and each TableCell.
const CONTENT_WIDTH_TWIPS = 9360;

function mapTable(node: PMLike): Table {
  const rows = (node.content as PMLike[] | undefined) ?? [];
  const firstRow = rows[0];
  const firstRowCells =
    (firstRow?.content as PMLike[] | undefined) ?? [];
  const colCount = Math.max(firstRowCells.length, 1);
  const colWidth = Math.floor(CONTENT_WIDTH_TWIPS / colCount);
  const columnWidths = Array(colCount).fill(colWidth);
  return new Table({
    width: { size: CONTENT_WIDTH_TWIPS, type: WidthType.DXA },
    columnWidths,
    rows: rows.map((r) => mapTableRow(r, colWidth)),
  });
}

function mapTableRow(row: PMLike, colWidth: number): TableRow {
  const cells = (row.content as PMLike[] | undefined) ?? [];
  return new TableRow({
    children: cells.map((c) => mapTableCell(c, colWidth)),
  });
}

function mapTableCell(cell: PMLike, colWidth: number): TableCell {
  const inner = (cell.content as PMLike[] | undefined) ?? [];
  const children: Paragraph[] = [];
  for (const node of inner) {
    if (node.type === "paragraph") {
      children.push(
        new Paragraph({
          children: mapInline(node.content as PMLike[] | undefined),
        }),
      );
    } else {
      const mapped = mapBlock(node);
      if (mapped instanceof Paragraph) children.push(mapped);
    }
  }
  if (children.length === 0) children.push(new Paragraph(""));
  return new TableCell({
    children,
    width: { size: colWidth, type: WidthType.DXA },
  });
}

function mapBlockquote(node: PMLike): Paragraph {
  const inlineSrc =
    (node.content as PMLike[] | undefined)?.find((c) => c.type === "paragraph")
      ?.content as PMLike[] | undefined;
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    children: mapInline(inlineSrc),
    indent: { left: 720 },
  });
}
