"use client";

import { useEffect, useState } from "react";
import { formatDistanceToNowStrict } from "date-fns";
import { getRegulationTranslation } from "@/lib/regwatch/regulation-translation-actions";

interface Props {
  regId: string;
  sourceLang: string;
}

interface State {
  loading: boolean;
  translatedText?: string;
  translatedAt?: string;
  fromCache?: boolean;
  error?: string;
  notNeeded?: boolean;
}

const LANG_LABEL: Record<string, string> = {
  ar: "Arabic",
  fr: "French",
  es: "Spanish",
  zh: "Chinese",
  de: "German",
  pt: "Portuguese",
  ru: "Russian",
};

/**
 * Machine-translation tab body. Calls the cached server action and
 * renders the English text below a prominently bolded legal
 * disclaimer. Translation is generated by Claude Sonnet via the
 * regulation-translation-actions server action, with the source PDF
 * pulled from the same cached Storage object the Original tab uses.
 *
 * The disclaimer copy is intentionally explicit about SparkLab LLC
 * not taking responsibility for misunderstandings, and tells users
 * to consult an Arabic-speaking engineering specialist. Always
 * visible at the top of the pane — does not collapse.
 */
export function RegulationTranslationPane({ regId, sourceLang }: Props) {
  const [state, setState] = useState<State>({ loading: true });

  useEffect(() => {
    let cancelled = false;
    setState({ loading: true });
    getRegulationTranslation({ regId })
      .then((r) => {
        if (cancelled) return;
        setState({
          loading: false,
          translatedText: r.translatedText,
          translatedAt: r.translatedAt,
          fromCache: r.fromCache,
          error: r.error,
          notNeeded: r.notNeeded,
        });
      })
      .catch((e: unknown) => {
        if (cancelled) return;
        setState({ loading: false, error: (e as Error).message });
      });
    return () => {
      cancelled = true;
    };
  }, [regId]);

  const sourceLangLabel = LANG_LABEL[sourceLang] ?? sourceLang.toUpperCase();

  return (
    <div className="space-y-4">
      <DisclaimerBanner sourceLangLabel={sourceLangLabel} />

      {state.loading && (
        <div className="rounded-md border border-card-border bg-card-bg/40 p-8 text-center text-xs text-muted">
          {sourceLang === "ar" ? "Translating from Arabic" : `Translating from ${sourceLangLabel}`}
          {" — this can take 10-30 seconds on first request. Cached after."}
        </div>
      )}

      {state.notNeeded && (
        <div className="rounded-md border border-brand-teal/40 bg-brand-teal/5 p-4 text-xs text-foreground">
          The source document is already in English. No translation is
          needed — see the <strong>Original</strong> tab.
        </div>
      )}

      {state.error && !state.loading && (
        <div className="rounded-md border border-red-500/40 bg-red-500/10 p-4 text-xs text-red-300">
          {state.error}
        </div>
      )}

      {state.translatedText && (
        <article className="rounded-xl border border-card-border bg-card-bg/40 p-5">
          <div className="mb-3 flex items-center justify-between gap-2 border-b border-card-border pb-2">
            <p className="text-[11px] text-muted">
              Machine translation · {sourceLangLabel} → English
              {state.fromCache && state.translatedAt && (
                <>
                  {" · cached "}
                  {formatDistanceToNowStrict(new Date(state.translatedAt), {
                    addSuffix: true,
                  })}
                </>
              )}
              {!state.fromCache && " · just generated"}
            </p>
          </div>
          <div className="prose prose-invert max-w-none whitespace-pre-wrap text-sm leading-relaxed text-foreground/90">
            {state.translatedText}
          </div>
        </article>
      )}
    </div>
  );
}

function DisclaimerBanner({ sourceLangLabel }: { sourceLangLabel: string }) {
  return (
    <div className="rounded-xl border-2 border-amber-500/60 bg-amber-500/10 p-4">
      <p className="text-[10px] font-bold uppercase tracking-wider text-amber-300">
        ⚠ Machine translation — read before relying on this
      </p>
      <p className="mt-2 text-sm font-bold leading-snug text-foreground">
        This is a machine-generated translation from {sourceLangLabel} produced
        by an AI language model. It is offered as a navigation aid only.
        It is <span className="underline">not a legally valid</span>{" "}
        rendering of the source regulation.
      </p>
      <p className="mt-2 text-xs leading-relaxed text-foreground/90">
        Before acting on anything in this translation, you{" "}
        <strong>must consult an {sourceLangLabel}-speaking engineering or
        legal specialist</strong> to confirm the meaning against the original
        Arabic source on the <strong>Original</strong> tab. Compliance
        evidence, audit submissions, and regulatory citations must use the
        canonical {sourceLangLabel} document — not this translation.
      </p>
      <p className="mt-2 text-[11px] leading-relaxed text-muted">
        <strong>SparkLab LLC (intelle.io) accepts no responsibility</strong>{" "}
        for misinterpretations, omissions, errors, or any losses or liability
        arising from reliance on this AI-generated translation. The
        translation is provided &ldquo;as is&rdquo; with no warranty of any
        kind. Use at your own risk.
      </p>
    </div>
  );
}
