/**
 * Interactive tutorial courses shown on /regwatch/tutorials and linked from the
 * Help drawer. Each course is split into per-surface SECTIONS (clips with a
 * baked Nova voiceover + a caption cue track), played back-to-back with a
 * Continue gate by <TutorialPlayer>.
 *
 * Section data (clips + cues) is generated by the pipeline in scripts/tutorials/
 * and committed to tutorials.data.json. A course with no sections yet renders as
 * "coming soon".
 */
import data from "./tutorials.data.json";

export const TUTORIAL_BUCKET = "regwatch-tutorials";

export interface Cue {
  start: number;
  end: number;
  text: string;
}
export interface TutorialSection {
  slug: string;
  title: string;
  /** object path within the public bucket, e.g. "tutorials/regulations/01-browse.mp4" */
  file: string;
  durationSec: number;
  /** Upload revision — appended as ?v= to bust browser/CDN cache after re-uploads. */
  rev?: number;
  cues: Cue[];
}
export interface TutorialCourse {
  slug: string;
  title: string;
  description: string;
  /** Empty until the course has been produced by the pipeline. */
  sections: TutorialSection[];
}

// Stable course list (order + copy). Sections merge in from the generated data.
const COURSE_META: { slug: string; title: string; description: string }[] = [
  {
    slug: "dashboard",
    title: "Your Dashboard",
    description:
      "The Vantage command center — headline numbers, your personal queue, compliance posture, a card per business line, and a live activity feed.",
  },
  {
    slug: "search",
    title: "AI Search",
    description:
      "One box to search regulations, policies, news, your company documents and assets — with Iris writing a cited answer and a side preview drawer.",
  },
  {
    slug: "regulations",
    title: "Exploring Regulations",
    description:
      "Browse the corpus by country, regulator and topic, read original and translated sources, and search with Iris.",
  },
  {
    slug: "monitor",
    title: "Monitoring Your Feed",
    description:
      "Your footprint-scored Relevance Feed, weekly recap, saved searches and alerts.",
  },
  {
    slug: "comply",
    title: "Managing Compliance",
    description:
      "Set up your footprint and asset hierarchy, then track obligations through review.",
  },
  {
    slug: "author",
    title: "Authoring Documents",
    description:
      "Draft, cite, version and approve company SOPs and policies in the in-app editor.",
  },
];

const generated = (data as { courses: TutorialCourse[] }).courses ?? [];

export const TUTORIAL_COURSES: TutorialCourse[] = COURSE_META.map((m) => {
  const g = generated.find((c) => c.slug === m.slug);
  return {
    slug: m.slug,
    title: g?.title ?? m.title,
    description: g?.description ?? m.description,
    sections: g?.sections ?? [],
  };
});

/** Public URL for a Storage object in the public tutorials bucket. */
export function tutorialUrl(file: string): string {
  const base = (process.env.NEXT_PUBLIC_SUPABASE_URL ?? "").replace(/\/$/, "");
  return `${base}/storage/v1/object/public/${TUTORIAL_BUCKET}/${file}`;
}

/** Cache-busted public URL for a section clip (appends the upload revision). */
export function sectionVideoUrl(section: TutorialSection): string {
  const url = tutorialUrl(section.file);
  return section.rev ? `${url}?v=${section.rev}` : url;
}

/** Human duration label across a course's sections. */
export function courseDurationLabel(course: TutorialCourse): string {
  const total = course.sections.reduce((n, s) => n + s.durationSec, 0);
  if (total <= 0) return "Coming soon";
  return total < 60 ? `~${Math.round(total)}s` : `~${Math.round(total / 60)} min`;
}
