-- ===========================================================================
-- Vantage — US CFR Title 14 (Aeronautics and Space) Part corpus (baked snapshot)
-- ---------------------------------------------------------------------------
-- One regulatory_item per PART (198 parts), parsed from the eCFR structure
-- API. Parts feed list/topics/search; the full section tree is built by the
-- ecfr-title-14 connector into regwatch.regulatory_sections (sections deep-link to a
-- small in-app page, then to ecfr.gov). body_text filled by the body backfill.
-- ===========================================================================

with reg as (select id from regwatch.regulators where slug = 'us-cfr-14')
insert into regwatch.regulatory_items
  (regulator_id, citation, slug, title, instrument_type, status, source_url, jurisdiction_code, topics)
select reg.id, v.citation, v.slug, v.title, 'secondary-legislation', 'in-force', v.source_url, 'US', v.topics
from reg, (values
    ('14 CFR Part 1', '14-cfr-part-1', 'Definitions and Abbreviations', 'https://www.ecfr.gov/current/title-14/part-1', '{"aviation"}'::text[]),
    ('14 CFR Part 3', '14-cfr-part-3', 'General Requirements', 'https://www.ecfr.gov/current/title-14/part-3', '{"aviation"}'::text[]),
    ('14 CFR Part 5', '14-cfr-part-5', 'Safety Management Systems', 'https://www.ecfr.gov/current/title-14/part-5', '{"aviation"}'::text[]),
    ('14 CFR Part 11', '14-cfr-part-11', 'General Rulemaking Procedures', 'https://www.ecfr.gov/current/title-14/part-11', '{"aviation"}'::text[]),
    ('14 CFR Part 13', '14-cfr-part-13', 'Investigative and Enforcement Procedures', 'https://www.ecfr.gov/current/title-14/part-13', '{"aviation"}'::text[]),
    ('14 CFR Part 14', '14-cfr-part-14', 'Rules Implementing the Equal Access to Justice Act of 1980', 'https://www.ecfr.gov/current/title-14/part-14', '{"aviation"}'::text[]),
    ('14 CFR Part 15', '14-cfr-part-15', 'Administrative Claims Under Federal Tort Claims Act', 'https://www.ecfr.gov/current/title-14/part-15', '{"aviation"}'::text[]),
    ('14 CFR Part 16', '14-cfr-part-16', 'Rules of Practice for Federally-Assisted Airport Enforcement Proceedings', 'https://www.ecfr.gov/current/title-14/part-16', '{"aviation"}'::text[]),
    ('14 CFR Part 17', '14-cfr-part-17', 'Procedures for Protests and Contract Disputes', 'https://www.ecfr.gov/current/title-14/part-17', '{"aviation"}'::text[]),
    ('14 CFR Part 21', '14-cfr-part-21', 'Certification Procedures for Products and Articles', 'https://www.ecfr.gov/current/title-14/part-21', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 22', '14-cfr-part-22', 'XXX', 'https://www.ecfr.gov/current/title-14/part-22', '{"aviation"}'::text[]),
    ('14 CFR Part 23', '14-cfr-part-23', 'Airworthiness Standards: Normal Category Airplanes', 'https://www.ecfr.gov/current/title-14/part-23', '{"aviation"}'::text[]),
    ('14 CFR Part 25', '14-cfr-part-25', 'Airworthiness Standards: Transport Category Airplanes', 'https://www.ecfr.gov/current/title-14/part-25', '{"aviation"}'::text[]),
    ('14 CFR Part 26', '14-cfr-part-26', 'Continued Airworthiness and Safety Improvements for Transport Category Airplanes', 'https://www.ecfr.gov/current/title-14/part-26', '{"aviation"}'::text[]),
    ('14 CFR Part 27', '14-cfr-part-27', 'Airworthiness Standards: Normal Category Rotorcraft', 'https://www.ecfr.gov/current/title-14/part-27', '{"aviation"}'::text[]),
    ('14 CFR Part 29', '14-cfr-part-29', 'Airworthiness Standards: Transport Category Rotorcraft', 'https://www.ecfr.gov/current/title-14/part-29', '{"aviation"}'::text[]),
    ('14 CFR Part 31', '14-cfr-part-31', 'Airworthiness Standards: Manned Free Balloons', 'https://www.ecfr.gov/current/title-14/part-31', '{"aviation"}'::text[]),
    ('14 CFR Part 33', '14-cfr-part-33', 'Airworthiness Standards: Aircraft Engines', 'https://www.ecfr.gov/current/title-14/part-33', '{"aviation"}'::text[]),
    ('14 CFR Part 34', '14-cfr-part-34', 'Fuel Venting and Exhaust Emission Requirements for Turbine Engine Powered Airplanes', 'https://www.ecfr.gov/current/title-14/part-34', '{"emissions","aviation"}'::text[]),
    ('14 CFR Part 35', '14-cfr-part-35', 'Airworthiness Standards: Propellers', 'https://www.ecfr.gov/current/title-14/part-35', '{"aviation"}'::text[]),
    ('14 CFR Part 36', '14-cfr-part-36', 'Noise Standards: Aircraft Type and Airworthiness Certification', 'https://www.ecfr.gov/current/title-14/part-36', '{"permitting","emissions","aviation"}'::text[]),
    ('14 CFR Part 38', '14-cfr-part-38', 'Airplane Fuel Efficiency Certification', 'https://www.ecfr.gov/current/title-14/part-38', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 39', '14-cfr-part-39', 'Airworthiness Directives', 'https://www.ecfr.gov/current/title-14/part-39', '{"aviation"}'::text[]),
    ('14 CFR Part 43', '14-cfr-part-43', 'Maintenance, Preventive Maintenance, Rebuilding, and Alteration', 'https://www.ecfr.gov/current/title-14/part-43', '{"aviation"}'::text[]),
    ('14 CFR Part 45', '14-cfr-part-45', 'Identification and Registration Marking', 'https://www.ecfr.gov/current/title-14/part-45', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 47', '14-cfr-part-47', 'Aircraft Registration', 'https://www.ecfr.gov/current/title-14/part-47', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 48', '14-cfr-part-48', 'Registration and Marking Requirements for Small Unmanned Aircraft', 'https://www.ecfr.gov/current/title-14/part-48', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 49', '14-cfr-part-49', 'Recording of Aircraft Titles and Security Documents', 'https://www.ecfr.gov/current/title-14/part-49', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 60', '14-cfr-part-60', 'Flight Simulation Training Device Initial and Continuing Qualification and Use', 'https://www.ecfr.gov/current/title-14/part-60', '{"aviation"}'::text[]),
    ('14 CFR Part 61', '14-cfr-part-61', 'Certification: Pilots, Flight Instructors, and Ground Instructors', 'https://www.ecfr.gov/current/title-14/part-61', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 63', '14-cfr-part-63', 'Certification: Flight Crewmembers Other Than Pilots', 'https://www.ecfr.gov/current/title-14/part-63', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 65', '14-cfr-part-65', 'Certification: Airmen Other Than Flight Crewmembers', 'https://www.ecfr.gov/current/title-14/part-65', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 67', '14-cfr-part-67', 'Medical Standards and Certification', 'https://www.ecfr.gov/current/title-14/part-67', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 68', '14-cfr-part-68', 'Requirements for Operating Certain Small Aircraft Without a Medical Certificate', 'https://www.ecfr.gov/current/title-14/part-68', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 71', '14-cfr-part-71', 'Designation of Class A, B, C, D, and E Airspace Areas; Air Traffic Service Routes; and Reporting Points', 'https://www.ecfr.gov/current/title-14/part-71', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 73', '14-cfr-part-73', 'Special Use Airspace', 'https://www.ecfr.gov/current/title-14/part-73', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 77', '14-cfr-part-77', 'Safe, Efficient Use, and Preservation of the Navigable Airspace', 'https://www.ecfr.gov/current/title-14/part-77', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 89', '14-cfr-part-89', 'Remote Identification of Unmanned Aircraft', 'https://www.ecfr.gov/current/title-14/part-89', '{"aviation"}'::text[]),
    ('14 CFR Part 91', '14-cfr-part-91', 'General Operating and Flight Rules', 'https://www.ecfr.gov/current/title-14/part-91', '{"aviation"}'::text[]),
    ('14 CFR Part 93', '14-cfr-part-93', 'Special Air Traffic Rules', 'https://www.ecfr.gov/current/title-14/part-93', '{"aviation"}'::text[]),
    ('14 CFR Part 95', '14-cfr-part-95', 'IFR Altitudes', 'https://www.ecfr.gov/current/title-14/part-95', '{"aviation"}'::text[]),
    ('14 CFR Part 97', '14-cfr-part-97', 'Standard Instrument Procedures', 'https://www.ecfr.gov/current/title-14/part-97', '{"aviation"}'::text[]),
    ('14 CFR Part 99', '14-cfr-part-99', 'Security Control of Air Traffic', 'https://www.ecfr.gov/current/title-14/part-99', '{"aviation"}'::text[]),
    ('14 CFR Part 101', '14-cfr-part-101', 'Moored Balloons, Kites, Amateur Rockets, and Unmanned Free Balloons', 'https://www.ecfr.gov/current/title-14/part-101', '{"aviation"}'::text[]),
    ('14 CFR Part 103', '14-cfr-part-103', 'Ultralight Vehicles', 'https://www.ecfr.gov/current/title-14/part-103', '{"aviation"}'::text[]),
    ('14 CFR Part 105', '14-cfr-part-105', 'Parachute Operations', 'https://www.ecfr.gov/current/title-14/part-105', '{"aviation"}'::text[]),
    ('14 CFR Part 107', '14-cfr-part-107', 'Small Unmanned Aircraft Systems', 'https://www.ecfr.gov/current/title-14/part-107', '{"aviation"}'::text[]),
    ('14 CFR Part 110', '14-cfr-part-110', 'General Requirements', 'https://www.ecfr.gov/current/title-14/part-110', '{"aviation"}'::text[]),
    ('14 CFR Part 111', '14-cfr-part-111', 'Pilot Records Database', 'https://www.ecfr.gov/current/title-14/part-111', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 117', '14-cfr-part-117', 'Flight and Duty Limitations and Rest Requirements: Flightcrew Members', 'https://www.ecfr.gov/current/title-14/part-117', '{"aviation"}'::text[]),
    ('14 CFR Part 119', '14-cfr-part-119', 'Certification: Air Carriers and Commercial Operators', 'https://www.ecfr.gov/current/title-14/part-119', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 120', '14-cfr-part-120', 'Drug and Alcohol Testing Program', 'https://www.ecfr.gov/current/title-14/part-120', '{"aviation"}'::text[]),
    ('14 CFR Part 121', '14-cfr-part-121', 'Operating Requirements: Domestic, Flag, and Supplemental Operations', 'https://www.ecfr.gov/current/title-14/part-121', '{"aviation"}'::text[]),
    ('14 CFR Part 125', '14-cfr-part-125', 'Certification and Operations: Aircraft Having a Seating Capacity of 20 or More Passengers or a Maximum Payload Capacity of 6,000 Pounds or More; and Rules Governing Persons on Board Such Aircraft', 'https://www.ecfr.gov/current/title-14/part-125', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 129', '14-cfr-part-129', 'Operations: Foreign Air Carriers and Foreign Operators of U.S.-Registered Aircraft Engaged in Common Carriage', 'https://www.ecfr.gov/current/title-14/part-129', '{"aviation"}'::text[]),
    ('14 CFR Part 133', '14-cfr-part-133', 'Rotorcraft External-Load Operations', 'https://www.ecfr.gov/current/title-14/part-133', '{"aviation"}'::text[]),
    ('14 CFR Part 135', '14-cfr-part-135', 'Operating Requirements: Commuter and on Demand Operations and Rules Governing Persons on Board Such Aircraft', 'https://www.ecfr.gov/current/title-14/part-135', '{"aviation"}'::text[]),
    ('14 CFR Part 136', '14-cfr-part-136', 'Commercial Air Tours and National Parks Air Tour Management', 'https://www.ecfr.gov/current/title-14/part-136', '{"aviation"}'::text[]),
    ('14 CFR Part 137', '14-cfr-part-137', 'Agricultural Aircraft Operations', 'https://www.ecfr.gov/current/title-14/part-137', '{"aviation"}'::text[]),
    ('14 CFR Part 139', '14-cfr-part-139', 'Certification of Airports', 'https://www.ecfr.gov/current/title-14/part-139', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 141', '14-cfr-part-141', 'Pilot Schools', 'https://www.ecfr.gov/current/title-14/part-141', '{"aviation"}'::text[]),
    ('14 CFR Part 142', '14-cfr-part-142', 'Training Centers', 'https://www.ecfr.gov/current/title-14/part-142', '{"aviation"}'::text[]),
    ('14 CFR Part 145', '14-cfr-part-145', 'Repair Stations', 'https://www.ecfr.gov/current/title-14/part-145', '{"aviation"}'::text[]),
    ('14 CFR Part 147', '14-cfr-part-147', 'Aviation Maintenance Technician Schools', 'https://www.ecfr.gov/current/title-14/part-147', '{"aviation"}'::text[]),
    ('14 CFR Part 150', '14-cfr-part-150', 'Airport Noise Compatibility Planning', 'https://www.ecfr.gov/current/title-14/part-150', '{"emissions","aviation"}'::text[]),
    ('14 CFR Part 151', '14-cfr-part-151', 'Federal Aid to Airports', 'https://www.ecfr.gov/current/title-14/part-151', '{"aviation"}'::text[]),
    ('14 CFR Part 152', '14-cfr-part-152', 'Airport Aid Program', 'https://www.ecfr.gov/current/title-14/part-152', '{"aviation"}'::text[]),
    ('14 CFR Part 153', '14-cfr-part-153', 'Airport Operations', 'https://www.ecfr.gov/current/title-14/part-153', '{"aviation"}'::text[]),
    ('14 CFR Part 155', '14-cfr-part-155', 'Release of Airport Property from Surplus Property Disposal Restrictions', 'https://www.ecfr.gov/current/title-14/part-155', '{"aviation"}'::text[]),
    ('14 CFR Part 156', '14-cfr-part-156', 'State Block Grant Pilot Program', 'https://www.ecfr.gov/current/title-14/part-156', '{"aviation"}'::text[]),
    ('14 CFR Part 157', '14-cfr-part-157', 'Notice of Construction, Alteration, Activation, and Deactivation of Airports', 'https://www.ecfr.gov/current/title-14/part-157', '{"aviation"}'::text[]),
    ('14 CFR Part 158', '14-cfr-part-158', 'Passenger Facility Charges (PFC''s)', 'https://www.ecfr.gov/current/title-14/part-158', '{"aviation"}'::text[]),
    ('14 CFR Part 161', '14-cfr-part-161', 'Notice and Approval of Airport Noise and Access Restrictions', 'https://www.ecfr.gov/current/title-14/part-161', '{"permitting","emissions","aviation"}'::text[]),
    ('14 CFR Part 169', '14-cfr-part-169', 'Expenditure of Federal Funds for Nonmilitary Airports or Air Navigation Facilities Thereon', 'https://www.ecfr.gov/current/title-14/part-169', '{"aviation"}'::text[]),
    ('14 CFR Part 170', '14-cfr-part-170', 'Establishment and Discontinuance Criteria for Air Traffic Control Services and Navigational Facilities', 'https://www.ecfr.gov/current/title-14/part-170', '{"aviation"}'::text[]),
    ('14 CFR Part 171', '14-cfr-part-171', 'Non-Federal Navigation Facilities', 'https://www.ecfr.gov/current/title-14/part-171', '{"aviation"}'::text[]),
    ('14 CFR Part 183', '14-cfr-part-183', 'Representatives of the Administrator', 'https://www.ecfr.gov/current/title-14/part-183', '{"aviation"}'::text[]),
    ('14 CFR Part 185', '14-cfr-part-185', 'Testimony by Employees and Production of Records in Legal Proceedings, and Service of Legal Process and Pleadings', 'https://www.ecfr.gov/current/title-14/part-185', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 187', '14-cfr-part-187', 'Fees', 'https://www.ecfr.gov/current/title-14/part-187', '{"aviation"}'::text[]),
    ('14 CFR Part 189', '14-cfr-part-189', 'Use of Federal Aviation Administration Communications System', 'https://www.ecfr.gov/current/title-14/part-189', '{"aviation"}'::text[]),
    ('14 CFR Part 193', '14-cfr-part-193', 'Protection of Voluntarily Submitted Information', 'https://www.ecfr.gov/current/title-14/part-193', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 194', '14-cfr-part-194', 'Special Federal Aviation Regulation No. 120—Powered-Lift: Pilot Certification and Training; Operations Requirements', 'https://www.ecfr.gov/current/title-14/part-194', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 198', '14-cfr-part-198', 'Aviation Insurance', 'https://www.ecfr.gov/current/title-14/part-198', '{"aviation"}'::text[]),
    ('14 CFR Part 200', '14-cfr-part-200', 'Definitions and Instructions', 'https://www.ecfr.gov/current/title-14/part-200', '{"aviation"}'::text[]),
    ('14 CFR Part 201', '14-cfr-part-201', 'Air Carrier Authority Under Subtitle VII of Title 49 of the United States Code', 'https://www.ecfr.gov/current/title-14/part-201', '{"aviation"}'::text[]),
    ('14 CFR Part 203', '14-cfr-part-203', 'Waiver of Warsaw Convention Liability Limits and Defenses', 'https://www.ecfr.gov/current/title-14/part-203', '{"aviation"}'::text[]),
    ('14 CFR Part 204', '14-cfr-part-204', 'Data to Support Fitness Determinations', 'https://www.ecfr.gov/current/title-14/part-204', '{"aviation"}'::text[]),
    ('14 CFR Part 205', '14-cfr-part-205', 'Aircraft Accident Liability Insurance', 'https://www.ecfr.gov/current/title-14/part-205', '{"aviation"}'::text[]),
    ('14 CFR Part 206', '14-cfr-part-206', 'Certificates of Public Convenience and Necessity: Special Authorizations and Exemptions', 'https://www.ecfr.gov/current/title-14/part-206', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 211', '14-cfr-part-211', 'Applications for Permits to Foreign Air Carriers', 'https://www.ecfr.gov/current/title-14/part-211', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 212', '14-cfr-part-212', 'Charter Rules for U.S. and Foreign Direct Air Carriers', 'https://www.ecfr.gov/current/title-14/part-212', '{"aviation"}'::text[]),
    ('14 CFR Part 213', '14-cfr-part-213', 'Terms, Conditions and Limitations of Foreign Air Carrier Permits', 'https://www.ecfr.gov/current/title-14/part-213', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 214', '14-cfr-part-214', 'Terms, Conditions, and Limitations of Foreign Air Carrier Permits Authorizing Charter Transportation Only', 'https://www.ecfr.gov/current/title-14/part-214', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 215', '14-cfr-part-215', 'Use and Change of Names of Air Carriers, Foreign Air Carriers and Commuter Air Carriers', 'https://www.ecfr.gov/current/title-14/part-215', '{"aviation"}'::text[]),
    ('14 CFR Part 216', '14-cfr-part-216', 'Commingling of Blind Sector Traffic by Foreign Air Carriers', 'https://www.ecfr.gov/current/title-14/part-216', '{"aviation"}'::text[]),
    ('14 CFR Part 217', '14-cfr-part-217', 'Reporting Traffic Statistics by Foreign Air Carriers in Civilian Scheduled, Charter, and Nonscheduled Services', 'https://www.ecfr.gov/current/title-14/part-217', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 218', '14-cfr-part-218', 'Lease by Foreign Air Carrier or Other Foreign Person of Aircraft with Crew', 'https://www.ecfr.gov/current/title-14/part-218', '{"aviation"}'::text[]),
    ('14 CFR Part 221', '14-cfr-part-221', 'Tariffs', 'https://www.ecfr.gov/current/title-14/part-221', '{"aviation"}'::text[]),
    ('14 CFR Part 222', '14-cfr-part-222', 'Intermodal Cargo Services by Foreign Air Carriers', 'https://www.ecfr.gov/current/title-14/part-222', '{"aviation"}'::text[]),
    ('14 CFR Part 223', '14-cfr-part-223', 'Free and Reduced-Rate Transportation', 'https://www.ecfr.gov/current/title-14/part-223', '{"aviation"}'::text[]),
    ('14 CFR Part 234', '14-cfr-part-234', 'Airline Service Quality Performance Reports', 'https://www.ecfr.gov/current/title-14/part-234', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 235', '14-cfr-part-235', 'Reports by Air Carriers on Incidents Involving Animals During Air Transport', 'https://www.ecfr.gov/current/title-14/part-235', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 240', '14-cfr-part-240', 'Inspection of Accounts and Property', 'https://www.ecfr.gov/current/title-14/part-240', '{"aviation"}'::text[]),
    ('14 CFR Part 241', '14-cfr-part-241', 'Uniform System of Accounts and Reports for Large Certificated Air Carriers', 'https://www.ecfr.gov/current/title-14/part-241', '{"permitting","reporting","aviation"}'::text[]),
    ('14 CFR Part 243', '14-cfr-part-243', 'Passenger Manifest Information', 'https://www.ecfr.gov/current/title-14/part-243', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 244', '14-cfr-part-244', 'Reporting Tarmac Delay Data', 'https://www.ecfr.gov/current/title-14/part-244', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 247', '14-cfr-part-247', 'Direct Airport-to-Airport Mileage Records', 'https://www.ecfr.gov/current/title-14/part-247', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 248', '14-cfr-part-248', 'Submission of Audit Reports', 'https://www.ecfr.gov/current/title-14/part-248', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 249', '14-cfr-part-249', 'Preservation of Air Carrier Records', 'https://www.ecfr.gov/current/title-14/part-249', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 250', '14-cfr-part-250', 'Oversales', 'https://www.ecfr.gov/current/title-14/part-250', '{"aviation"}'::text[]),
    ('14 CFR Part 251', '14-cfr-part-251', 'Carriage of Musical Instruments', 'https://www.ecfr.gov/current/title-14/part-251', '{"aviation"}'::text[]),
    ('14 CFR Part 252', '14-cfr-part-252', 'Smoking Aboard Aircraft', 'https://www.ecfr.gov/current/title-14/part-252', '{"aviation"}'::text[]),
    ('14 CFR Part 253', '14-cfr-part-253', 'Notice of Terms of Contract of Carriage', 'https://www.ecfr.gov/current/title-14/part-253', '{"aviation"}'::text[]),
    ('14 CFR Part 254', '14-cfr-part-254', 'Domestic Baggage Liability', 'https://www.ecfr.gov/current/title-14/part-254', '{"aviation"}'::text[]),
    ('14 CFR Part 256', '14-cfr-part-256', 'Electronic Airline Information Systems', 'https://www.ecfr.gov/current/title-14/part-256', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 257', '14-cfr-part-257', 'Disclosure of Code-Sharing Arrangements and Long-Term Wet Leases', 'https://www.ecfr.gov/current/title-14/part-257', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 258', '14-cfr-part-258', 'Disclosure of Change-of-Gauge Services', 'https://www.ecfr.gov/current/title-14/part-258', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 259', '14-cfr-part-259', 'Enhanced Protections for Airline Passengers', 'https://www.ecfr.gov/current/title-14/part-259', '{"aviation"}'::text[]),
    ('14 CFR Part 260', '14-cfr-part-260', 'Refunds for Airline Fare and Ancillary Service Fees', 'https://www.ecfr.gov/current/title-14/part-260', '{"aviation"}'::text[]),
    ('14 CFR Part 262', '14-cfr-part-262', 'Travel Credits or Vouchers Due to a Serious Communicable Disease', 'https://www.ecfr.gov/current/title-14/part-262', '{"aviation"}'::text[]),
    ('14 CFR Part 271', '14-cfr-part-271', 'Guidelines for Subsidizing Air Carriers Providing Essential Air Transportation', 'https://www.ecfr.gov/current/title-14/part-271', '{"aviation"}'::text[]),
    ('14 CFR Part 291', '14-cfr-part-291', 'Cargo Operations in Interstate Air Transportation', 'https://www.ecfr.gov/current/title-14/part-291', '{"aviation"}'::text[]),
    ('14 CFR Part 292', '14-cfr-part-292', 'International Cargo Transportation', 'https://www.ecfr.gov/current/title-14/part-292', '{"aviation"}'::text[]),
    ('14 CFR Part 293', '14-cfr-part-293', 'International Passenger Transportation', 'https://www.ecfr.gov/current/title-14/part-293', '{"aviation"}'::text[]),
    ('14 CFR Part 294', '14-cfr-part-294', 'Canadian Charter Air Taxi Operators', 'https://www.ecfr.gov/current/title-14/part-294', '{"aviation"}'::text[]),
    ('14 CFR Part 295', '14-cfr-part-295', 'Air Charter Brokers', 'https://www.ecfr.gov/current/title-14/part-295', '{"aviation"}'::text[]),
    ('14 CFR Part 296', '14-cfr-part-296', 'Indirect Air Transportation of Property', 'https://www.ecfr.gov/current/title-14/part-296', '{"aviation"}'::text[]),
    ('14 CFR Part 297', '14-cfr-part-297', 'Foreign Air Freight Forwarders and Foreign Cooperative Shippers Associations', 'https://www.ecfr.gov/current/title-14/part-297', '{"aviation"}'::text[]),
    ('14 CFR Part 298', '14-cfr-part-298', 'Exemptions for Air Taxi and Commuter Air Carrier Operations', 'https://www.ecfr.gov/current/title-14/part-298', '{"aviation"}'::text[]),
    ('14 CFR Part 300', '14-cfr-part-300', 'Rules of Conduct in DOT Proceedings Under This Chapter', 'https://www.ecfr.gov/current/title-14/part-300', '{"aviation"}'::text[]),
    ('14 CFR Part 302', '14-cfr-part-302', 'Rules of Practice in Proceedings', 'https://www.ecfr.gov/current/title-14/part-302', '{"aviation"}'::text[]),
    ('14 CFR Part 303', '14-cfr-part-303', 'Review of Air Carrier Agreements', 'https://www.ecfr.gov/current/title-14/part-303', '{"aviation"}'::text[]),
    ('14 CFR Part 305', '14-cfr-part-305', 'Rules of Practice in Informal Nonpublic Investigations', 'https://www.ecfr.gov/current/title-14/part-305', '{"reporting","aviation"}'::text[]),
    ('14 CFR Part 313', '14-cfr-part-313', 'Implementation of the Energy Policy and Conservation Act', 'https://www.ecfr.gov/current/title-14/part-313', '{"aviation"}'::text[]),
    ('14 CFR Part 323', '14-cfr-part-323', 'Terminations, Suspensions, and Reductions of Service', 'https://www.ecfr.gov/current/title-14/part-323', '{"aviation"}'::text[]),
    ('14 CFR Part 325', '14-cfr-part-325', 'Essential Air Service Procedures', 'https://www.ecfr.gov/current/title-14/part-325', '{"aviation"}'::text[]),
    ('14 CFR Part 372', '14-cfr-part-372', 'Overseas Military Personnel Charters', 'https://www.ecfr.gov/current/title-14/part-372', '{"aviation"}'::text[]),
    ('14 CFR Part 374', '14-cfr-part-374', 'Implementation of the Consumer Credit Protection Act with Respect to Air Carriers and Foreign Air Carriers', 'https://www.ecfr.gov/current/title-14/part-374', '{"aviation"}'::text[]),
    ('14 CFR Part 374a', '14-cfr-part-374a', 'Extension of Credit by Airlines to Federal Political Candidates', 'https://www.ecfr.gov/current/title-14/part-374a', '{"aviation"}'::text[]),
    ('14 CFR Part 375', '14-cfr-part-375', 'Navigation of Foreign Civil Aircraft Within the United States', 'https://www.ecfr.gov/current/title-14/part-375', '{"aviation"}'::text[]),
    ('14 CFR Part 377', '14-cfr-part-377', 'Continuance of Expired Authorizations by Operation of Law Pending Final Determination of Applications for Renewal Thereof', 'https://www.ecfr.gov/current/title-14/part-377', '{"permitting","aviation"}'::text[]),
    ('14 CFR Part 380', '14-cfr-part-380', 'Public Charters', 'https://www.ecfr.gov/current/title-14/part-380', '{"aviation"}'::text[]),
    ('14 CFR Part 381', '14-cfr-part-381', 'Special Event Tours', 'https://www.ecfr.gov/current/title-14/part-381', '{"aviation"}'::text[]),
    ('14 CFR Part 382', '14-cfr-part-382', 'Nondiscrimination on the Basis of Disability in Air Travel', 'https://www.ecfr.gov/current/title-14/part-382', '{"aviation"}'::text[]),
    ('14 CFR Part 383', '14-cfr-part-383', 'Civil Penalties', 'https://www.ecfr.gov/current/title-14/part-383', '{"aviation"}'::text[]),
    ('14 CFR Part 385', '14-cfr-part-385', 'Staff Assignments and Review of Action Under Assignments', 'https://www.ecfr.gov/current/title-14/part-385', '{"aviation"}'::text[]),
    ('14 CFR Part 389', '14-cfr-part-389', 'Fees and Charges for Special Services', 'https://www.ecfr.gov/current/title-14/part-389', '{"aviation"}'::text[]),
    ('14 CFR Part 398', '14-cfr-part-398', 'Guidelines for Individual Determinations of Basic Essential Air Service', 'https://www.ecfr.gov/current/title-14/part-398', '{"aviation"}'::text[]),
    ('14 CFR Part 399', '14-cfr-part-399', 'Statements of General Policy', 'https://www.ecfr.gov/current/title-14/part-399', '{"aviation"}'::text[]),
    ('14 CFR Part 400', '14-cfr-part-400', 'Basis and Scope', 'https://www.ecfr.gov/current/title-14/part-400', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 401', '14-cfr-part-401', 'Organization and Definitions', 'https://www.ecfr.gov/current/title-14/part-401', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 402', '14-cfr-part-402', 'General Requirements', 'https://www.ecfr.gov/current/title-14/part-402', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 404', '14-cfr-part-404', 'Petition and Rulemaking Procedures', 'https://www.ecfr.gov/current/title-14/part-404', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 405', '14-cfr-part-405', 'Compliance and Enforcement', 'https://www.ecfr.gov/current/title-14/part-405', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 406', '14-cfr-part-406', 'Investigations, Enforcement, and Administrative Review', 'https://www.ecfr.gov/current/title-14/part-406', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 413', '14-cfr-part-413', 'License Application Procedures', 'https://www.ecfr.gov/current/title-14/part-413', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 414', '14-cfr-part-414', 'Safety Element Approvals', 'https://www.ecfr.gov/current/title-14/part-414', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 420', '14-cfr-part-420', 'License to Operate a Launch Site', 'https://www.ecfr.gov/current/title-14/part-420', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 433', '14-cfr-part-433', 'License to Operate a Reentry Site', 'https://www.ecfr.gov/current/title-14/part-433', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 437', '14-cfr-part-437', 'Experimental Permits', 'https://www.ecfr.gov/current/title-14/part-437', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 440', '14-cfr-part-440', 'Financial Responsibility', 'https://www.ecfr.gov/current/title-14/part-440', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 450', '14-cfr-part-450', 'Launch and Reentry License Requirements', 'https://www.ecfr.gov/current/title-14/part-450', '{"permitting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 460', '14-cfr-part-460', 'Human Space Flight Requirements', 'https://www.ecfr.gov/current/title-14/part-460', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1201', '14-cfr-part-1201', 'Statement of Organization and General Information', 'https://www.ecfr.gov/current/title-14/part-1201', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1203', '14-cfr-part-1203', 'Information Security Program', 'https://www.ecfr.gov/current/title-14/part-1203', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1203a', '14-cfr-part-1203a', 'NASA Security Areas', 'https://www.ecfr.gov/current/title-14/part-1203a', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1203b', '14-cfr-part-1203b', 'Security Programs; Arrest Authority and Use of Force by NASA Security Force Personnel', 'https://www.ecfr.gov/current/title-14/part-1203b', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1204', '14-cfr-part-1204', 'Administrative Authority and Policy', 'https://www.ecfr.gov/current/title-14/part-1204', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1206', '14-cfr-part-1206', 'Procedures for Disclosure of Records Under the Freedom of Information Act (FOIA)', 'https://www.ecfr.gov/current/title-14/part-1206', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1207', '14-cfr-part-1207', 'Standards of Conduct', 'https://www.ecfr.gov/current/title-14/part-1207', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1208', '14-cfr-part-1208', 'Uniform Relocation Assistance and Real Property Acquisition for Federal and Federally Assisted Programs', 'https://www.ecfr.gov/current/title-14/part-1208', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1209', '14-cfr-part-1209', 'Boards and Committees', 'https://www.ecfr.gov/current/title-14/part-1209', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1212', '14-cfr-part-1212', 'Privacy Act—NASA Regulations', 'https://www.ecfr.gov/current/title-14/part-1212', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1213', '14-cfr-part-1213', 'Release of Information to News and Information Media', 'https://www.ecfr.gov/current/title-14/part-1213', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1214', '14-cfr-part-1214', 'Space Flight', 'https://www.ecfr.gov/current/title-14/part-1214', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1215', '14-cfr-part-1215', 'Tracking and Data Relay Satellite System (TDRSS)', 'https://www.ecfr.gov/current/title-14/part-1215', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1216', '14-cfr-part-1216', 'Environmental Quality', 'https://www.ecfr.gov/current/title-14/part-1216', '{"emissions","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1217', '14-cfr-part-1217', 'Duty-Free Entry of Space Articles', 'https://www.ecfr.gov/current/title-14/part-1217', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1221', '14-cfr-part-1221', 'The NASA Seal and Other Devices, and the Congressional Space Medal of Honor', 'https://www.ecfr.gov/current/title-14/part-1221', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1230', '14-cfr-part-1230', 'Protection of Human Subjects', 'https://www.ecfr.gov/current/title-14/part-1230', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1232', '14-cfr-part-1232', 'Care and Use of Animals in the Conduct of NASA Activities', 'https://www.ecfr.gov/current/title-14/part-1232', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1240', '14-cfr-part-1240', 'Inventions and Contributions', 'https://www.ecfr.gov/current/title-14/part-1240', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1241', '14-cfr-part-1241', 'To Research, Evaluate, Assess, and Treat (TREAT) Astronauts', 'https://www.ecfr.gov/current/title-14/part-1241', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1245', '14-cfr-part-1245', 'Patents and Other Intellectual Property Rights', 'https://www.ecfr.gov/current/title-14/part-1245', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1250', '14-cfr-part-1250', 'Nondiscrimination in Federally-Assisted Programs of NASA—Effectuation of Title VI of the Civil Rights Act of 1964', 'https://www.ecfr.gov/current/title-14/part-1250', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1251', '14-cfr-part-1251', 'Nondiscrimination on Basis of Disability', 'https://www.ecfr.gov/current/title-14/part-1251', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1252', '14-cfr-part-1252', 'Nondiscrimination on the Basis of Age in Programs or Activities Receiving Federal Financial Assistance', 'https://www.ecfr.gov/current/title-14/part-1252', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1253', '14-cfr-part-1253', 'Nondiscrimination on the Basis of Sex in Education Programs or Activities Receiving Federal Financial Assistance', 'https://www.ecfr.gov/current/title-14/part-1253', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1259', '14-cfr-part-1259', 'National Space Grant College and Fellowship Program', 'https://www.ecfr.gov/current/title-14/part-1259', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1261', '14-cfr-part-1261', 'Processing of Monetary Claims (General)', 'https://www.ecfr.gov/current/title-14/part-1261', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1262', '14-cfr-part-1262', 'Equal Access to Justice Act in Agency Proceedings', 'https://www.ecfr.gov/current/title-14/part-1262', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1263', '14-cfr-part-1263', 'Demand for Information or Testimony Served on Agency Employees; Procedures', 'https://www.ecfr.gov/current/title-14/part-1263', '{"reporting","aviation","aerospace"}'::text[]),
    ('14 CFR Part 1264', '14-cfr-part-1264', 'Implementation of the Program Fraud Civil Penalties Act of 1986', 'https://www.ecfr.gov/current/title-14/part-1264', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1266', '14-cfr-part-1266', 'Cross-Waiver of Liability', 'https://www.ecfr.gov/current/title-14/part-1266', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1271', '14-cfr-part-1271', 'New Restrictions on Lobbying', 'https://www.ecfr.gov/current/title-14/part-1271', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1275', '14-cfr-part-1275', 'Research Misconduct', 'https://www.ecfr.gov/current/title-14/part-1275', '{"aviation","aerospace"}'::text[]),
    ('14 CFR Part 1300', '14-cfr-part-1300', 'Aviation Disaster Relief—Air Carrier Guarantee Loan Program', 'https://www.ecfr.gov/current/title-14/part-1300', '{"aviation"}'::text[]),
    ('14 CFR Part 1310', '14-cfr-part-1310', 'Air Carrier Guarantee Loan Program Administrative Regulations and Amendment or Waiver of a Term or Condition of Guaranteed Loan', 'https://www.ecfr.gov/current/title-14/part-1310', '{"aviation"}'::text[])
) as v(citation, slug, title, source_url, topics)
on conflict (regulator_id, citation) do update
  set title = excluded.title, slug = excluded.slug, source_url = excluded.source_url,
      topics = excluded.topics, last_changed_at = now();
