-- ===========================================================================
-- Vantage — US CFR Title 10 (Energy) Part corpus (baked snapshot)
-- ---------------------------------------------------------------------------
-- One regulatory_item per PART of Title 10 (180 parts), parsed from the
-- eCFR structure API. Parts are the citeable unit that feeds list/topics/search;
-- the full Title->Chapter->...->Section tree is built separately by the
-- ecfr-title-10 connector into regwatch.regulatory_sections (sections deep-link
-- to ecfr.gov). body_text is filled later by the body-enrich pass.
-- ===========================================================================

with cfr10 as (select id from regwatch.regulators where slug = 'us-cfr-10')
insert into regwatch.regulatory_items
  (regulator_id, citation, slug, title, instrument_type, status, source_url, jurisdiction_code, topics)
select cfr10.id, v.citation, v.slug, v.title, 'secondary-legislation', 'in-force', v.source_url, 'US', v.topics
from cfr10, (values
    ('10 CFR Part 1', '10-cfr-part-1', 'Statement of Organization and General Information', 'https://www.ecfr.gov/current/title-10/part-1', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 2', '10-cfr-part-2', 'Agency Rules of Practice and Procedure', 'https://www.ecfr.gov/current/title-10/part-2', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 4', '10-cfr-part-4', 'Nondiscrimination in Federally Assisted Programs or Activities Receiving Federal Financial Assistance from the Commission', 'https://www.ecfr.gov/current/title-10/part-4', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 5', '10-cfr-part-5', 'Nondiscrimination on the Basis of Sex in Education Programs or Activities Receiving Federal Financial Assistance', 'https://www.ecfr.gov/current/title-10/part-5', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 7', '10-cfr-part-7', 'Advisory Committees', 'https://www.ecfr.gov/current/title-10/part-7', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 9', '10-cfr-part-9', 'Public Records', 'https://www.ecfr.gov/current/title-10/part-9', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 10', '10-cfr-part-10', 'Criteria and Procedures for Determining Eligibility for Access to Restricted Data or National Security Information or an Employment Clearance', 'https://www.ecfr.gov/current/title-10/part-10', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 11', '10-cfr-part-11', 'Criteria and Procedures for Determining Eligibility for Access to or Control over Special Nuclear Material', 'https://www.ecfr.gov/current/title-10/part-11', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 12', '10-cfr-part-12', 'Implementation of the Equal Access to Justice Act in Agency Proceedings', 'https://www.ecfr.gov/current/title-10/part-12', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 13', '10-cfr-part-13', 'Administrative Remedies for False Claims and Statements', 'https://www.ecfr.gov/current/title-10/part-13', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 14', '10-cfr-part-14', 'Administrative Claims Under Federal Tort Claims Act', 'https://www.ecfr.gov/current/title-10/part-14', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 15', '10-cfr-part-15', 'Debt Collection Procedures', 'https://www.ecfr.gov/current/title-10/part-15', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 16', '10-cfr-part-16', 'Salary Offset Procedures for Collecting Debts Owed by Federal Employees to the Federal Government', 'https://www.ecfr.gov/current/title-10/part-16', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 19', '10-cfr-part-19', 'Notices, Instructions and Reports to Workers: Inspection and Investigations', 'https://www.ecfr.gov/current/title-10/part-19', '{"energy","nuclear","reporting","worker-safety"}'::text[]),
    ('10 CFR Part 20', '10-cfr-part-20', 'Standards for Protection Against Radiation', 'https://www.ecfr.gov/current/title-10/part-20', '{"energy","nuclear","radiation"}'::text[]),
    ('10 CFR Part 21', '10-cfr-part-21', 'Reporting of Defects and Noncompliance', 'https://www.ecfr.gov/current/title-10/part-21', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 25', '10-cfr-part-25', 'Access Authorization', 'https://www.ecfr.gov/current/title-10/part-25', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 26', '10-cfr-part-26', 'Fitness for Duty Programs', 'https://www.ecfr.gov/current/title-10/part-26', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 30', '10-cfr-part-30', 'Rules of General Applicability to Domestic Licensing of Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-30', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 31', '10-cfr-part-31', 'General Domestic Licenses for Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-31', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 32', '10-cfr-part-32', 'Specific Domestic Licenses to Manufacture or Transfer Certain Items Containing Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-32', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 33', '10-cfr-part-33', 'Specific Domestic Licenses of Broad Scope for Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-33', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 34', '10-cfr-part-34', 'Licenses for Industrial Radiography and Radiation Safety Requirements for Industrial Radiographic Operations', 'https://www.ecfr.gov/current/title-10/part-34', '{"energy","nuclear","radiation","permitting","worker-safety"}'::text[]),
    ('10 CFR Part 35', '10-cfr-part-35', 'Medical Use of Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-35', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 36', '10-cfr-part-36', 'Licenses and Radiation Safety Requirements for Irradiators', 'https://www.ecfr.gov/current/title-10/part-36', '{"energy","nuclear","radiation","permitting","worker-safety"}'::text[]),
    ('10 CFR Part 37', '10-cfr-part-37', 'Physical Protection of Category 1 and Category 2 Quantities of Radioactive Material', 'https://www.ecfr.gov/current/title-10/part-37', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 39', '10-cfr-part-39', 'Licenses and Radiation Safety Requirements for Well Logging', 'https://www.ecfr.gov/current/title-10/part-39', '{"energy","nuclear","radiation","permitting","worker-safety"}'::text[]),
    ('10 CFR Part 40', '10-cfr-part-40', 'Domestic Licensing of Source Material', 'https://www.ecfr.gov/current/title-10/part-40', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 50', '10-cfr-part-50', 'Domestic Licensing of Production and Utilization Facilities', 'https://www.ecfr.gov/current/title-10/part-50', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 51', '10-cfr-part-51', 'Environmental Protection Regulations for Domestic Licensing and Related Regulatory Functions', 'https://www.ecfr.gov/current/title-10/part-51', '{"energy","nuclear","emissions","permitting"}'::text[]),
    ('10 CFR Part 52', '10-cfr-part-52', 'Licenses, Certifications, and Approvals for Nuclear Power Plants', 'https://www.ecfr.gov/current/title-10/part-52', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 53', '10-cfr-part-53', 'Risk-Informed, Technology-Inclusive Regulatory Framework for Commercial Nuclear Plants', 'https://www.ecfr.gov/current/title-10/part-53', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 54', '10-cfr-part-54', 'Requirements for Renewal of Operating Licenses for Nuclear Power Plants', 'https://www.ecfr.gov/current/title-10/part-54', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 55', '10-cfr-part-55', 'Operators'' Licenses', 'https://www.ecfr.gov/current/title-10/part-55', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 60', '10-cfr-part-60', 'Disposal of High-Level Radioactive Wastes in Geologic Repositories', 'https://www.ecfr.gov/current/title-10/part-60', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 61', '10-cfr-part-61', 'Licensing Requirements for Land Disposal of Radioactive Waste', 'https://www.ecfr.gov/current/title-10/part-61', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 62', '10-cfr-part-62', 'Criteria and Procedures for Emergency Access to Non-Federal and Regional Low-Level Waste Disposal Facilities', 'https://www.ecfr.gov/current/title-10/part-62', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 63', '10-cfr-part-63', 'Disposal of High-Level Radioactive Wastes in a Geologic Repository at Yucca Mountain, Nevada', 'https://www.ecfr.gov/current/title-10/part-63', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 70', '10-cfr-part-70', 'Domestic Licensing of Special Nuclear Material', 'https://www.ecfr.gov/current/title-10/part-70', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 71', '10-cfr-part-71', 'Packaging and Transportation of Radioactive Material', 'https://www.ecfr.gov/current/title-10/part-71', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 72', '10-cfr-part-72', 'Licensing Requirements for the Independent Storage of Spent Nuclear Fuel, High-Level Radioactive Waste, and Reactor-Related Greater Than Class C Waste', 'https://www.ecfr.gov/current/title-10/part-72', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 73', '10-cfr-part-73', 'Physical Protection of Plants and Materials', 'https://www.ecfr.gov/current/title-10/part-73', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 74', '10-cfr-part-74', 'Material Control and Accounting of Special Nuclear Material', 'https://www.ecfr.gov/current/title-10/part-74', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 75', '10-cfr-part-75', 'Safeguards on Nuclear Material—Implementation of Safeguards Agreements Between the United States and the International Atomic Energy Agency', 'https://www.ecfr.gov/current/title-10/part-75', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 76', '10-cfr-part-76', 'Certification of Gaseous Diffusion Plants', 'https://www.ecfr.gov/current/title-10/part-76', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 81', '10-cfr-part-81', 'Standard Specifications for the Granting of Patent Licenses', 'https://www.ecfr.gov/current/title-10/part-81', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 95', '10-cfr-part-95', 'Facility Security Clearance and Safeguarding of National Security Information and Restricted Data', 'https://www.ecfr.gov/current/title-10/part-95', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 100', '10-cfr-part-100', 'Reactor Site Criteria', 'https://www.ecfr.gov/current/title-10/part-100', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 110', '10-cfr-part-110', 'Export and Import of Nuclear Equipment and Material', 'https://www.ecfr.gov/current/title-10/part-110', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 140', '10-cfr-part-140', 'Financial Protection Requirements and Indemnity Agreements', 'https://www.ecfr.gov/current/title-10/part-140', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 150', '10-cfr-part-150', 'Exemptions and Continued Regulatory Authority in Agreement States and in Offshore Waters Under Section 274', 'https://www.ecfr.gov/current/title-10/part-150', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 160', '10-cfr-part-160', 'Trespassing on Commission Property', 'https://www.ecfr.gov/current/title-10/part-160', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 170', '10-cfr-part-170', 'Fees for Facilities, Materials, Import and Export Licenses, and Other Regulatory Services Under the Atomic Energy Act of 1954, as Amended', 'https://www.ecfr.gov/current/title-10/part-170', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 171', '10-cfr-part-171', 'Annual Fees for Reactor Licenses and Fuel Cycle Licenses and Materials Licenses, Including Holders of Certificates of Compliance, Registrations, and Quality Assurance Program Approvals and Government Agencies Licensed by the NRC', 'https://www.ecfr.gov/current/title-10/part-171', '{"energy","nuclear","permitting"}'::text[]),
    ('10 CFR Part 202', '10-cfr-part-202', 'Production or Disclosure of Material or Information', 'https://www.ecfr.gov/current/title-10/part-202', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 205', '10-cfr-part-205', 'Administrative Procedures and Sanctions', 'https://www.ecfr.gov/current/title-10/part-205', '{"energy"}'::text[]),
    ('10 CFR Part 207', '10-cfr-part-207', 'Collection of Information', 'https://www.ecfr.gov/current/title-10/part-207', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 209', '10-cfr-part-209', 'International Voluntary Agreements', 'https://www.ecfr.gov/current/title-10/part-209', '{"energy"}'::text[]),
    ('10 CFR Part 210', '10-cfr-part-210', 'General Allocation and Price Rules', 'https://www.ecfr.gov/current/title-10/part-210', '{"energy"}'::text[]),
    ('10 CFR Part 212', '10-cfr-part-212', 'Mandatory Petroleum Price Regulations', 'https://www.ecfr.gov/current/title-10/part-212', '{"energy"}'::text[]),
    ('10 CFR Part 215', '10-cfr-part-215', 'Collection of Foreign Oil Supply Agreement Information', 'https://www.ecfr.gov/current/title-10/part-215', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 216', '10-cfr-part-216', 'Materials Allocation and Priority Performance Under Contracts or Orders to Maximize Domestic Energy Supplies', 'https://www.ecfr.gov/current/title-10/part-216', '{"energy"}'::text[]),
    ('10 CFR Part 217', '10-cfr-part-217', 'Energy Priorities and Allocations System', 'https://www.ecfr.gov/current/title-10/part-217', '{"energy"}'::text[]),
    ('10 CFR Part 218', '10-cfr-part-218', 'Standby Mandatory International Oil Allocation', 'https://www.ecfr.gov/current/title-10/part-218', '{"energy"}'::text[]),
    ('10 CFR Part 221', '10-cfr-part-221', 'Priority Supply of Crude Oil and Petroleum Products to the Department of Defense Under the Defense Production Act', 'https://www.ecfr.gov/current/title-10/part-221', '{"energy"}'::text[]),
    ('10 CFR Part 300', '10-cfr-part-300', 'Voluntary Greenhouse Gas Reporting Program: General Guidelines', 'https://www.ecfr.gov/current/title-10/part-300', '{"energy","emissions","reporting"}'::text[]),
    ('10 CFR Part 420', '10-cfr-part-420', 'State Energy Program', 'https://www.ecfr.gov/current/title-10/part-420', '{"energy"}'::text[]),
    ('10 CFR Part 429', '10-cfr-part-429', 'Certification, Compliance, and Enforcement for Consumer Products and Commercial and Industrial Equipment', 'https://www.ecfr.gov/current/title-10/part-429', '{"energy","permitting"}'::text[]),
    ('10 CFR Part 430', '10-cfr-part-430', 'Energy Conservation Program for Consumer Products', 'https://www.ecfr.gov/current/title-10/part-430', '{"energy"}'::text[]),
    ('10 CFR Part 431', '10-cfr-part-431', 'Energy Efficiency Program for Certain Commercial and Industrial Equipment', 'https://www.ecfr.gov/current/title-10/part-431', '{"energy"}'::text[]),
    ('10 CFR Part 433', '10-cfr-part-433', 'Energy Efficiency Standards for the Design and Construction of New Federal Commercial and Multi-Family High-Rise Residential Buildings', 'https://www.ecfr.gov/current/title-10/part-433', '{"energy"}'::text[]),
    ('10 CFR Part 434', '10-cfr-part-434', 'Energy Code for New Federal Commercial and Multi-Family High Rise Residential Buildings', 'https://www.ecfr.gov/current/title-10/part-434', '{"energy"}'::text[]),
    ('10 CFR Part 435', '10-cfr-part-435', 'Energy Efficiency Standards for the Design and Construction of New Federal Low-Rise Residential Buildings', 'https://www.ecfr.gov/current/title-10/part-435', '{"energy"}'::text[]),
    ('10 CFR Part 436', '10-cfr-part-436', 'Federal Energy Management and Planning Programs', 'https://www.ecfr.gov/current/title-10/part-436', '{"energy"}'::text[]),
    ('10 CFR Part 440', '10-cfr-part-440', 'Weatherization Assistance for Low-Income Persons', 'https://www.ecfr.gov/current/title-10/part-440', '{"energy"}'::text[]),
    ('10 CFR Part 451', '10-cfr-part-451', 'Renewable Energy Production Incentives', 'https://www.ecfr.gov/current/title-10/part-451', '{"energy"}'::text[]),
    ('10 CFR Part 452', '10-cfr-part-452', 'Production Incentives for Cellulosic Biofuels', 'https://www.ecfr.gov/current/title-10/part-452', '{"energy"}'::text[]),
    ('10 CFR Part 460', '10-cfr-part-460', 'Energy Conservation Standards for Manufactured Homes', 'https://www.ecfr.gov/current/title-10/part-460', '{"energy"}'::text[]),
    ('10 CFR Part 470', '10-cfr-part-470', 'Appropriate Technology Small Grants Program', 'https://www.ecfr.gov/current/title-10/part-470', '{"energy"}'::text[]),
    ('10 CFR Part 473', '10-cfr-part-473', 'Automotive Propulsion Research and Development', 'https://www.ecfr.gov/current/title-10/part-473', '{"energy"}'::text[]),
    ('10 CFR Part 474', '10-cfr-part-474', 'Electric and Hybrid Vehicle Research, Development, and Demonstration Program; Petroleum-Equivalent Fuel Economy Calculation', 'https://www.ecfr.gov/current/title-10/part-474', '{"energy"}'::text[]),
    ('10 CFR Part 490', '10-cfr-part-490', 'Alternative Fuel Transportation Program', 'https://www.ecfr.gov/current/title-10/part-490', '{"energy"}'::text[]),
    ('10 CFR Part 500', '10-cfr-part-500', 'Definitions', 'https://www.ecfr.gov/current/title-10/part-500', '{"energy"}'::text[]),
    ('10 CFR Part 501', '10-cfr-part-501', 'Administrative Procedures and Sanctions', 'https://www.ecfr.gov/current/title-10/part-501', '{"energy"}'::text[]),
    ('10 CFR Part 503', '10-cfr-part-503', 'New Facilities', 'https://www.ecfr.gov/current/title-10/part-503', '{"energy"}'::text[]),
    ('10 CFR Part 504', '10-cfr-part-504', 'Existing Powerplants', 'https://www.ecfr.gov/current/title-10/part-504', '{"energy"}'::text[]),
    ('10 CFR Part 580', '10-cfr-part-580', 'Curtailment Priorities for Essential Agricultural Uses', 'https://www.ecfr.gov/current/title-10/part-580', '{"energy"}'::text[]),
    ('10 CFR Part 590', '10-cfr-part-590', 'Administrative Procedures with Respect to the Import and Export of Natural Gas', 'https://www.ecfr.gov/current/title-10/part-590', '{"energy"}'::text[]),
    ('10 CFR Part 601', '10-cfr-part-601', 'New Restrictions on Lobbying', 'https://www.ecfr.gov/current/title-10/part-601', '{"energy"}'::text[]),
    ('10 CFR Part 602', '10-cfr-part-602', 'Epidemiology and Other Health Studies Financial Assistance Program', 'https://www.ecfr.gov/current/title-10/part-602', '{"energy"}'::text[]),
    ('10 CFR Part 605', '10-cfr-part-605', 'The Office of Science Financial Assistance Program', 'https://www.ecfr.gov/current/title-10/part-605', '{"energy"}'::text[]),
    ('10 CFR Part 609', '10-cfr-part-609', 'Loan Guarantees for Clean Energy Projects', 'https://www.ecfr.gov/current/title-10/part-609', '{"energy"}'::text[]),
    ('10 CFR Part 611', '10-cfr-part-611', 'Advanced Technology Vehicles Manufacturer Assistance Program', 'https://www.ecfr.gov/current/title-10/part-611', '{"energy"}'::text[]),
    ('10 CFR Part 612', '10-cfr-part-612', 'Recapture of Civil Nuclear Credits', 'https://www.ecfr.gov/current/title-10/part-612', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 622', '10-cfr-part-622', 'Contractual Provisions', 'https://www.ecfr.gov/current/title-10/part-622', '{"energy"}'::text[]),
    ('10 CFR Part 624', '10-cfr-part-624', 'Contract Clauses', 'https://www.ecfr.gov/current/title-10/part-624', '{"energy"}'::text[]),
    ('10 CFR Part 625', '10-cfr-part-625', 'Price Competitive Sale of Strategic Petroleum Reserve Petroleum', 'https://www.ecfr.gov/current/title-10/part-625', '{"energy"}'::text[]),
    ('10 CFR Part 626', '10-cfr-part-626', 'Procedures for Acquisition of Petroleum for the Strategic Petroleum Reserve', 'https://www.ecfr.gov/current/title-10/part-626', '{"energy"}'::text[]),
    ('10 CFR Part 706', '10-cfr-part-706', 'Security Policies and Practices Relating to Labor-Management Relations', 'https://www.ecfr.gov/current/title-10/part-706', '{"energy"}'::text[]),
    ('10 CFR Part 707', '10-cfr-part-707', 'Workplace Substance Abuse Programs at DOE Sites', 'https://www.ecfr.gov/current/title-10/part-707', '{"energy"}'::text[]),
    ('10 CFR Part 708', '10-cfr-part-708', 'DOE Contractor Employee Protection Program', 'https://www.ecfr.gov/current/title-10/part-708', '{"energy"}'::text[]),
    ('10 CFR Part 709', '10-cfr-part-709', 'Counterintelligence Evaluation Program', 'https://www.ecfr.gov/current/title-10/part-709', '{"energy"}'::text[]),
    ('10 CFR Part 710', '10-cfr-part-710', 'Procedures for Determining Eligibility for Access to Classified Matter and Special Nuclear Material or Eligibility to Hold a Sensitive Position', 'https://www.ecfr.gov/current/title-10/part-710', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 712', '10-cfr-part-712', 'Human Reliability Program', 'https://www.ecfr.gov/current/title-10/part-712', '{"energy"}'::text[]),
    ('10 CFR Part 715', '10-cfr-part-715', 'Definition of Nonrecourse Project-Financed', 'https://www.ecfr.gov/current/title-10/part-715', '{"energy"}'::text[]),
    ('10 CFR Part 719', '10-cfr-part-719', 'Contractor Legal Management Requirements', 'https://www.ecfr.gov/current/title-10/part-719', '{"energy"}'::text[]),
    ('10 CFR Part 725', '10-cfr-part-725', 'Permits for Access to Restricted Data', 'https://www.ecfr.gov/current/title-10/part-725', '{"energy","permitting"}'::text[]),
    ('10 CFR Part 727', '10-cfr-part-727', 'Consent for Access to Information on Department of Energy Computers', 'https://www.ecfr.gov/current/title-10/part-727', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 733', '10-cfr-part-733', 'Allegations of Research Misconduct', 'https://www.ecfr.gov/current/title-10/part-733', '{"energy"}'::text[]),
    ('10 CFR Part 745', '10-cfr-part-745', 'Protection of Human Subjects', 'https://www.ecfr.gov/current/title-10/part-745', '{"energy","worker-safety"}'::text[]),
    ('10 CFR Part 760', '10-cfr-part-760', 'Domestic Uranium Program', 'https://www.ecfr.gov/current/title-10/part-760', '{"energy"}'::text[]),
    ('10 CFR Part 765', '10-cfr-part-765', 'Reimbursement for Costs of Remedial Action at Active Uranium and Thorium Processing Sites', 'https://www.ecfr.gov/current/title-10/part-765', '{"energy"}'::text[]),
    ('10 CFR Part 766', '10-cfr-part-766', 'Uranium Enrichment Decontamination and Decommissioning Fund; Procedures for Special Assessment of Domestic Utilities', 'https://www.ecfr.gov/current/title-10/part-766', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 770', '10-cfr-part-770', 'Transfer of Real Property at Defense Nuclear Facilities for Economic Development', 'https://www.ecfr.gov/current/title-10/part-770', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 780', '10-cfr-part-780', 'Patent Compensation Board Regulations', 'https://www.ecfr.gov/current/title-10/part-780', '{"energy"}'::text[]),
    ('10 CFR Part 781', '10-cfr-part-781', 'DOE Patent Licensing Regulations', 'https://www.ecfr.gov/current/title-10/part-781', '{"energy","permitting"}'::text[]),
    ('10 CFR Part 782', '10-cfr-part-782', 'Claims for Patent and Copyright Infringement', 'https://www.ecfr.gov/current/title-10/part-782', '{"energy"}'::text[]),
    ('10 CFR Part 783', '10-cfr-part-783', 'Waiver of Patent Rights', 'https://www.ecfr.gov/current/title-10/part-783', '{"energy"}'::text[]),
    ('10 CFR Part 784', '10-cfr-part-784', 'Patent Waiver Regulation', 'https://www.ecfr.gov/current/title-10/part-784', '{"energy"}'::text[]),
    ('10 CFR Part 800', '10-cfr-part-800', 'Loans for Bid or Proposal Preparation by Minority Business Enterprises Seeking DOE Contracts and Assistance', 'https://www.ecfr.gov/current/title-10/part-800', '{"energy"}'::text[]),
    ('10 CFR Part 810', '10-cfr-part-810', 'Assistance to Foreign Atomic Energy Activities', 'https://www.ecfr.gov/current/title-10/part-810', '{"energy"}'::text[]),
    ('10 CFR Part 820', '10-cfr-part-820', 'Procedural Rules for DOE Nuclear Activities', 'https://www.ecfr.gov/current/title-10/part-820', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 821', '10-cfr-part-821', 'Implementing Voluntary Agreements Under the Defense Production Act', 'https://www.ecfr.gov/current/title-10/part-821', '{"energy"}'::text[]),
    ('10 CFR Part 824', '10-cfr-part-824', 'Procedural Rules for the Assessment of Civil Penalties for Classified Information Security Violations', 'https://www.ecfr.gov/current/title-10/part-824', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 830', '10-cfr-part-830', 'Nuclear Safety Management', 'https://www.ecfr.gov/current/title-10/part-830', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 835', '10-cfr-part-835', 'Occupational Radiation Protection', 'https://www.ecfr.gov/current/title-10/part-835', '{"energy","radiation","worker-safety"}'::text[]),
    ('10 CFR Part 840', '10-cfr-part-840', 'Extraordinary Nuclear Occurrences', 'https://www.ecfr.gov/current/title-10/part-840', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 850', '10-cfr-part-850', 'Chronic Beryllium Disease Prevention Program', 'https://www.ecfr.gov/current/title-10/part-850', '{"energy"}'::text[]),
    ('10 CFR Part 851', '10-cfr-part-851', 'Worker Safety and Health Program', 'https://www.ecfr.gov/current/title-10/part-851', '{"energy","worker-safety"}'::text[]),
    ('10 CFR Part 860', '10-cfr-part-860', 'Trespassing on Department of Energy Property', 'https://www.ecfr.gov/current/title-10/part-860', '{"energy"}'::text[]),
    ('10 CFR Part 861', '10-cfr-part-861', 'Control of Traffic at Nevada Test Site', 'https://www.ecfr.gov/current/title-10/part-861', '{"energy"}'::text[]),
    ('10 CFR Part 862', '10-cfr-part-862', 'Restrictions on Aircraft Landing and Air Delivery at Department of Energy Nuclear Sites', 'https://www.ecfr.gov/current/title-10/part-862', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 871', '10-cfr-part-871', 'Air Transportation of Plutonium', 'https://www.ecfr.gov/current/title-10/part-871', '{"energy"}'::text[]),
    ('10 CFR Part 900', '10-cfr-part-900', 'Coordination of Federal Authorizations for Electric Transmission Facilities', 'https://www.ecfr.gov/current/title-10/part-900', '{"energy"}'::text[]),
    ('10 CFR Part 903', '10-cfr-part-903', 'Power and Transmission Rates', 'https://www.ecfr.gov/current/title-10/part-903', '{"energy"}'::text[]),
    ('10 CFR Part 904', '10-cfr-part-904', 'General Regulations for the Charges for the Sale of Power from the Boulder Canyon Project', 'https://www.ecfr.gov/current/title-10/part-904', '{"energy"}'::text[]),
    ('10 CFR Part 905', '10-cfr-part-905', 'Energy Planning and Management Program', 'https://www.ecfr.gov/current/title-10/part-905', '{"energy"}'::text[]),
    ('10 CFR Part 950', '10-cfr-part-950', 'Standby Support for Certain Nuclear Plant Delays', 'https://www.ecfr.gov/current/title-10/part-950', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 960', '10-cfr-part-960', 'General Guidelines for the Preliminary Screening of Potential Sites for a Nuclear Waste Repository', 'https://www.ecfr.gov/current/title-10/part-960', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 961', '10-cfr-part-961', 'Standard Contract for Disposal of Spent Nuclear Fuel and/or High-Level Radioactive Waste', 'https://www.ecfr.gov/current/title-10/part-961', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 962', '10-cfr-part-962', 'Byproduct Material', 'https://www.ecfr.gov/current/title-10/part-962', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 963', '10-cfr-part-963', 'Yucca Mountain Site Suitability Guidelines', 'https://www.ecfr.gov/current/title-10/part-963', '{"energy"}'::text[]),
    ('10 CFR Part 1002', '10-cfr-part-1002', 'Official Seal and Distinguishing Flag', 'https://www.ecfr.gov/current/title-10/part-1002', '{"energy"}'::text[]),
    ('10 CFR Part 1003', '10-cfr-part-1003', 'Office of Hearings and Appeals Procedural Regulations', 'https://www.ecfr.gov/current/title-10/part-1003', '{"energy"}'::text[]),
    ('10 CFR Part 1004', '10-cfr-part-1004', 'Freedom of Information Act (FOIA)', 'https://www.ecfr.gov/current/title-10/part-1004', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 1005', '10-cfr-part-1005', 'Intergovernmental Review of Department of Energy Programs and Activities', 'https://www.ecfr.gov/current/title-10/part-1005', '{"energy"}'::text[]),
    ('10 CFR Part 1008', '10-cfr-part-1008', 'Records Maintained on Individuals (Privacy Act)', 'https://www.ecfr.gov/current/title-10/part-1008', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 1009', '10-cfr-part-1009', 'General Policy for Pricing and Charging for Materials and Services Sold by DOE', 'https://www.ecfr.gov/current/title-10/part-1009', '{"energy"}'::text[]),
    ('10 CFR Part 1010', '10-cfr-part-1010', 'Conduct of Employees and Former Employees', 'https://www.ecfr.gov/current/title-10/part-1010', '{"energy"}'::text[]),
    ('10 CFR Part 1013', '10-cfr-part-1013', 'Program Fraud Civil Remedies and Procedures', 'https://www.ecfr.gov/current/title-10/part-1013', '{"energy"}'::text[]),
    ('10 CFR Part 1014', '10-cfr-part-1014', 'Administrative Claims Under Federal Tort Claims Act', 'https://www.ecfr.gov/current/title-10/part-1014', '{"energy"}'::text[]),
    ('10 CFR Part 1015', '10-cfr-part-1015', 'Collection of Claims Owed the United States', 'https://www.ecfr.gov/current/title-10/part-1015', '{"energy"}'::text[]),
    ('10 CFR Part 1016', '10-cfr-part-1016', 'Safeguarding of Restricted Data by Access Permittees', 'https://www.ecfr.gov/current/title-10/part-1016', '{"energy","permitting"}'::text[]),
    ('10 CFR Part 1017', '10-cfr-part-1017', 'Identification and Protection of Unclassified Controlled Nuclear Information', 'https://www.ecfr.gov/current/title-10/part-1017', '{"energy","nuclear","reporting","worker-safety"}'::text[]),
    ('10 CFR Part 1021', '10-cfr-part-1021', 'National Environmental Policy Act Implementing Procedures', 'https://www.ecfr.gov/current/title-10/part-1021', '{"energy","emissions"}'::text[]),
    ('10 CFR Part 1022', '10-cfr-part-1022', 'Compliance with Floodplain and Wetland Environmental Review Requirements', 'https://www.ecfr.gov/current/title-10/part-1022', '{"energy","emissions"}'::text[]),
    ('10 CFR Part 1039', '10-cfr-part-1039', 'Uniform Relocation Assistance and Real Property Acquisition for Federal and Federally Assisted Programs', 'https://www.ecfr.gov/current/title-10/part-1039', '{"energy"}'::text[]),
    ('10 CFR Part 1040', '10-cfr-part-1040', 'Nondiscrimination in Federally Assisted Programs or Activities', 'https://www.ecfr.gov/current/title-10/part-1040', '{"energy"}'::text[]),
    ('10 CFR Part 1041', '10-cfr-part-1041', 'Enforcement of Nondiscrimination on the Basis of Handicap in Programs or Activities Conducted by the Department of Energy', 'https://www.ecfr.gov/current/title-10/part-1041', '{"energy"}'::text[]),
    ('10 CFR Part 1042', '10-cfr-part-1042', 'Nondiscrimination on the Basis of Sex in Education Programs or Activities Receiving Federal Financial Assistance', 'https://www.ecfr.gov/current/title-10/part-1042', '{"energy"}'::text[]),
    ('10 CFR Part 1044', '10-cfr-part-1044', 'Security Requirements for Protected Disclosures Under Section 3164 of the National Defense Authorization Act for Fiscal Year 2000', 'https://www.ecfr.gov/current/title-10/part-1044', '{"energy","reporting"}'::text[]),
    ('10 CFR Part 1045', '10-cfr-part-1045', 'Nuclear Classification and Declassification', 'https://www.ecfr.gov/current/title-10/part-1045', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 1046', '10-cfr-part-1046', 'Medical, Physical Readiness, Training, and Access Authorization Standards for Protective Force Personnel', 'https://www.ecfr.gov/current/title-10/part-1046', '{"energy"}'::text[]),
    ('10 CFR Part 1047', '10-cfr-part-1047', 'Limited Arrest Authority and Use of Force by Protective Force Officers', 'https://www.ecfr.gov/current/title-10/part-1047', '{"energy"}'::text[]),
    ('10 CFR Part 1048', '10-cfr-part-1048', 'Trespassing on Strategic Petroleum Reserve Facilities and Other Property', 'https://www.ecfr.gov/current/title-10/part-1048', '{"energy"}'::text[]),
    ('10 CFR Part 1049', '10-cfr-part-1049', 'Limited Arrest Authority and Use of Force by Protective Force Officers of the Strategic Petroleum Reserve', 'https://www.ecfr.gov/current/title-10/part-1049', '{"energy"}'::text[]),
    ('10 CFR Part 1050', '10-cfr-part-1050', 'Foreign Gifts and Decorations', 'https://www.ecfr.gov/current/title-10/part-1050', '{"energy"}'::text[]),
    ('10 CFR Part 1060', '10-cfr-part-1060', 'Payment of Travel Expenses of Persons Who Are Not Government Employees', 'https://www.ecfr.gov/current/title-10/part-1060', '{"energy"}'::text[]),
    ('10 CFR Part 1061', '10-cfr-part-1061', 'XXX', 'https://www.ecfr.gov/current/title-10/part-1061', '{"energy"}'::text[]),
    ('10 CFR Part 1303', '10-cfr-part-1303', 'Public Information and Requests', 'https://www.ecfr.gov/current/title-10/part-1303', '{"energy","nuclear","reporting"}'::text[]),
    ('10 CFR Part 1304', '10-cfr-part-1304', 'Privacy Act of 1974', 'https://www.ecfr.gov/current/title-10/part-1304', '{"energy","nuclear"}'::text[]),
    ('10 CFR Part 1703', '10-cfr-part-1703', 'Public Information and Requests', 'https://www.ecfr.gov/current/title-10/part-1703', '{"energy","nuclear","reporting","worker-safety"}'::text[]),
    ('10 CFR Part 1704', '10-cfr-part-1704', 'Rules Implementing the Government in the Sunshine Act', 'https://www.ecfr.gov/current/title-10/part-1704', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1705', '10-cfr-part-1705', 'Privacy Act', 'https://www.ecfr.gov/current/title-10/part-1705', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1706', '10-cfr-part-1706', 'Organizational and Consultant Conflicts of Interests', 'https://www.ecfr.gov/current/title-10/part-1706', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1707', '10-cfr-part-1707', 'Testimony by DNFSB Employees and Production of Official Records in Legal Proceedings', 'https://www.ecfr.gov/current/title-10/part-1707', '{"energy","nuclear","reporting","worker-safety"}'::text[]),
    ('10 CFR Part 1708', '10-cfr-part-1708', 'Procedures for Safety Investigations', 'https://www.ecfr.gov/current/title-10/part-1708', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1709', '10-cfr-part-1709', 'Debt Collection Procedures', 'https://www.ecfr.gov/current/title-10/part-1709', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1710', '10-cfr-part-1710', 'Federal Employee Salary Offset Procedures for the Collection of a Debt Owed to the Federal Government', 'https://www.ecfr.gov/current/title-10/part-1710', '{"energy","nuclear","worker-safety"}'::text[]),
    ('10 CFR Part 1800', '10-cfr-part-1800', 'Declaration of Party State Eligibility for Northeast Interstate Low-Level Radioactive Waste Compact', 'https://www.ecfr.gov/current/title-10/part-1800', '{"energy","nuclear"}'::text[])
) as v(citation, slug, title, source_url, topics)
on conflict (regulator_id, citation) do update
  set title = excluded.title,
      slug = excluded.slug,
      source_url = excluded.source_url,
      topics = excluded.topics,
      last_changed_at = now();
