-- ===========================================================================
-- Vantage — US CFR Title 21 (Food and Drugs) Part corpus (baked snapshot)
-- ---------------------------------------------------------------------------
-- One regulatory_item per PART (263 parts), parsed from the eCFR structure
-- API. Parts feed list/topics/search; the full section tree is built by the
-- ecfr-title-21 connector into regwatch.regulatory_sections (sections deep-link to a
-- small in-app page, then to ecfr.gov). body_text filled by the body backfill.
-- ===========================================================================

with reg as (select id from regwatch.regulators where slug = 'us-cfr-21')
insert into regwatch.regulatory_items
  (regulator_id, citation, slug, title, instrument_type, status, source_url, jurisdiction_code, topics)
select reg.id, v.citation, v.slug, v.title, 'secondary-legislation', 'in-force', v.source_url, 'US', v.topics
from reg, (values
    ('21 CFR Part 1', '21-cfr-part-1', 'General Enforcement Regulations', 'https://www.ecfr.gov/current/title-21/part-1', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 2', '21-cfr-part-2', 'General Administrative Rulings and Decisions', 'https://www.ecfr.gov/current/title-21/part-2', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 3', '21-cfr-part-3', 'Product Jurisdiction', 'https://www.ecfr.gov/current/title-21/part-3', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 4', '21-cfr-part-4', 'Regulation of Combination Products', 'https://www.ecfr.gov/current/title-21/part-4', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 5', '21-cfr-part-5', 'Organization', 'https://www.ecfr.gov/current/title-21/part-5', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 7', '21-cfr-part-7', 'Enforcement Policy', 'https://www.ecfr.gov/current/title-21/part-7', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 10', '21-cfr-part-10', 'Administrative Practices and Procedures', 'https://www.ecfr.gov/current/title-21/part-10', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 11', '21-cfr-part-11', 'Electronic Records; Electronic Signatures', 'https://www.ecfr.gov/current/title-21/part-11', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 12', '21-cfr-part-12', 'Formal Evidentiary Public Hearing', 'https://www.ecfr.gov/current/title-21/part-12', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 13', '21-cfr-part-13', 'Public Hearing Before a Public Board of Inquiry', 'https://www.ecfr.gov/current/title-21/part-13', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 14', '21-cfr-part-14', 'Public Hearing Before a Public Advisory Committee', 'https://www.ecfr.gov/current/title-21/part-14', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 15', '21-cfr-part-15', 'Public Hearing Before the Commissioner', 'https://www.ecfr.gov/current/title-21/part-15', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 16', '21-cfr-part-16', 'Regulatory Hearing Before the Food and Drug Administration', 'https://www.ecfr.gov/current/title-21/part-16', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 17', '21-cfr-part-17', 'Civil Money Penalties Hearings', 'https://www.ecfr.gov/current/title-21/part-17', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 19', '21-cfr-part-19', 'Standards of Conduct and Conflicts of Interest', 'https://www.ecfr.gov/current/title-21/part-19', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 20', '21-cfr-part-20', 'Public Information', 'https://www.ecfr.gov/current/title-21/part-20', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 21', '21-cfr-part-21', 'Protection of Privacy', 'https://www.ecfr.gov/current/title-21/part-21', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 25', '21-cfr-part-25', 'Environmental Impact Considerations', 'https://www.ecfr.gov/current/title-21/part-25', '{"emissions","food-safety","drugs"}'::text[]),
    ('21 CFR Part 50', '21-cfr-part-50', 'Protection of Human Subjects', 'https://www.ecfr.gov/current/title-21/part-50', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 54', '21-cfr-part-54', 'Financial Disclosure by Clinical Investigators', 'https://www.ecfr.gov/current/title-21/part-54', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 56', '21-cfr-part-56', 'Institutional Review Boards', 'https://www.ecfr.gov/current/title-21/part-56', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 58', '21-cfr-part-58', 'Good Laboratory Practice for Nonclinical Laboratory Studies', 'https://www.ecfr.gov/current/title-21/part-58', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 60', '21-cfr-part-60', 'Patent Term Restoration', 'https://www.ecfr.gov/current/title-21/part-60', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 70', '21-cfr-part-70', 'Color Additives', 'https://www.ecfr.gov/current/title-21/part-70', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 71', '21-cfr-part-71', 'Color Additive Petitions', 'https://www.ecfr.gov/current/title-21/part-71', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 73', '21-cfr-part-73', 'Listing of Color Additives Exempt from Certification', 'https://www.ecfr.gov/current/title-21/part-73', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 74', '21-cfr-part-74', 'Listing of Color Additives Subject to Certification', 'https://www.ecfr.gov/current/title-21/part-74', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 80', '21-cfr-part-80', 'Color Additive Certification', 'https://www.ecfr.gov/current/title-21/part-80', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 81', '21-cfr-part-81', 'General Specifications and General Restrictions for Provisional Color Additives for Use in Foods, Drugs, and Cosmetics', 'https://www.ecfr.gov/current/title-21/part-81', '{"food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 82', '21-cfr-part-82', 'Listing of Certified Provisionally Listed Colors and Specifications', 'https://www.ecfr.gov/current/title-21/part-82', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 99', '21-cfr-part-99', 'Dissemination of Information on Unapproved/New Uses for Marketed Drugs, Biologics, and Devices', 'https://www.ecfr.gov/current/title-21/part-99', '{"reporting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 100', '21-cfr-part-100', 'General', 'https://www.ecfr.gov/current/title-21/part-100', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 101', '21-cfr-part-101', 'Food Labeling', 'https://www.ecfr.gov/current/title-21/part-101', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 102', '21-cfr-part-102', 'Common or Usual Name for Nonstandardized Foods', 'https://www.ecfr.gov/current/title-21/part-102', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 104', '21-cfr-part-104', 'Nutritional Quality Guidelines for Foods', 'https://www.ecfr.gov/current/title-21/part-104', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 105', '21-cfr-part-105', 'Foods for Special Dietary Use', 'https://www.ecfr.gov/current/title-21/part-105', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 106', '21-cfr-part-106', 'Infant Formula Requirements Pertaining to Current Good Manufacturing Practice, Quality Control Procedures, Quality Factors, Records and Reports, and Notifications', 'https://www.ecfr.gov/current/title-21/part-106', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 107', '21-cfr-part-107', 'Infant Formula', 'https://www.ecfr.gov/current/title-21/part-107', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 108', '21-cfr-part-108', 'Emergency Permit Control', 'https://www.ecfr.gov/current/title-21/part-108', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 109', '21-cfr-part-109', 'Unavoidable Contaminants in Food for Human Consumption and Food-Packaging Material', 'https://www.ecfr.gov/current/title-21/part-109', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 110', '21-cfr-part-110', 'Current Good Manufacturing Practice in Manufacturing, Packing, or Holding Human Food', 'https://www.ecfr.gov/current/title-21/part-110', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 111', '21-cfr-part-111', 'Current Good Manufacturing Practice in Manufacturing, Packaging, Labeling, or Holding Operations for Dietary Supplements', 'https://www.ecfr.gov/current/title-21/part-111', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 112', '21-cfr-part-112', 'Standards for the Growing, Harvesting, Packing, and Holding of Produce for Human Consumption', 'https://www.ecfr.gov/current/title-21/part-112', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 113', '21-cfr-part-113', 'Thermally Processed Low-Acid Foods Packaged in Hermetically Sealed Containers', 'https://www.ecfr.gov/current/title-21/part-113', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 114', '21-cfr-part-114', 'Acidified Foods', 'https://www.ecfr.gov/current/title-21/part-114', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 115', '21-cfr-part-115', 'Shell Eggs', 'https://www.ecfr.gov/current/title-21/part-115', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 117', '21-cfr-part-117', 'Current Good Manufacturing Practice, Hazard Analysis, and Risk-Based Preventive Controls for Human Food', 'https://www.ecfr.gov/current/title-21/part-117', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 118', '21-cfr-part-118', 'Production, Storage, and Transportation of Shell Eggs', 'https://www.ecfr.gov/current/title-21/part-118', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 119', '21-cfr-part-119', 'Dietary Supplements That Present a Significant or Unreasonable Risk', 'https://www.ecfr.gov/current/title-21/part-119', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 120', '21-cfr-part-120', 'Hazard Analysis and Critical Control Point (HACCP) Systems', 'https://www.ecfr.gov/current/title-21/part-120', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 121', '21-cfr-part-121', 'Mitigation Strategies to Protect Food Against Intentional Adulteration', 'https://www.ecfr.gov/current/title-21/part-121', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 123', '21-cfr-part-123', 'Fish and Fishery Products', 'https://www.ecfr.gov/current/title-21/part-123', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 129', '21-cfr-part-129', 'Processing and Bottling of Bottled Drinking Water', 'https://www.ecfr.gov/current/title-21/part-129', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 130', '21-cfr-part-130', 'Food Standards: General', 'https://www.ecfr.gov/current/title-21/part-130', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 131', '21-cfr-part-131', 'Milk and Cream', 'https://www.ecfr.gov/current/title-21/part-131', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 133', '21-cfr-part-133', 'Cheeses and Related Cheese Products', 'https://www.ecfr.gov/current/title-21/part-133', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 135', '21-cfr-part-135', 'Frozen Desserts', 'https://www.ecfr.gov/current/title-21/part-135', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 136', '21-cfr-part-136', 'Bakery Products', 'https://www.ecfr.gov/current/title-21/part-136', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 137', '21-cfr-part-137', 'Cereal Flours and Related Products', 'https://www.ecfr.gov/current/title-21/part-137', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 139', '21-cfr-part-139', 'Macaroni and Noodle Products', 'https://www.ecfr.gov/current/title-21/part-139', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 145', '21-cfr-part-145', 'Canned Fruits', 'https://www.ecfr.gov/current/title-21/part-145', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 146', '21-cfr-part-146', 'Canned Fruit Juices', 'https://www.ecfr.gov/current/title-21/part-146', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 150', '21-cfr-part-150', 'Fruit Butters, Jellies, Preserves, and Related Products', 'https://www.ecfr.gov/current/title-21/part-150', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 155', '21-cfr-part-155', 'Canned Vegetables', 'https://www.ecfr.gov/current/title-21/part-155', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 156', '21-cfr-part-156', 'Vegetable Juices', 'https://www.ecfr.gov/current/title-21/part-156', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 158', '21-cfr-part-158', 'Frozen Vegetables', 'https://www.ecfr.gov/current/title-21/part-158', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 160', '21-cfr-part-160', 'Eggs and Egg Products', 'https://www.ecfr.gov/current/title-21/part-160', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 161', '21-cfr-part-161', 'Fish and Shellfish', 'https://www.ecfr.gov/current/title-21/part-161', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 163', '21-cfr-part-163', 'Cacao Products', 'https://www.ecfr.gov/current/title-21/part-163', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 164', '21-cfr-part-164', 'Tree Nut and Peanut Products', 'https://www.ecfr.gov/current/title-21/part-164', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 165', '21-cfr-part-165', 'Beverages', 'https://www.ecfr.gov/current/title-21/part-165', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 166', '21-cfr-part-166', 'Margarine', 'https://www.ecfr.gov/current/title-21/part-166', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 168', '21-cfr-part-168', 'Sweeteners and Table Sirups', 'https://www.ecfr.gov/current/title-21/part-168', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 169', '21-cfr-part-169', 'Food Dressings and Flavorings', 'https://www.ecfr.gov/current/title-21/part-169', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 170', '21-cfr-part-170', 'Food Additives', 'https://www.ecfr.gov/current/title-21/part-170', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 171', '21-cfr-part-171', 'Food Additive Petitions', 'https://www.ecfr.gov/current/title-21/part-171', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 172', '21-cfr-part-172', 'Food Additives Permitted for Direct Addition to Food for Human Consumption', 'https://www.ecfr.gov/current/title-21/part-172', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 173', '21-cfr-part-173', 'Secondary Direct Food Additives Permitted in Food for Human Consumption', 'https://www.ecfr.gov/current/title-21/part-173', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 174', '21-cfr-part-174', 'Indirect Food Additives: General', 'https://www.ecfr.gov/current/title-21/part-174', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 175', '21-cfr-part-175', 'Indirect Food Additives: Adhesives and Components of Coatings', 'https://www.ecfr.gov/current/title-21/part-175', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 176', '21-cfr-part-176', 'Indirect Food Additives: Paper and Paperboard Components', 'https://www.ecfr.gov/current/title-21/part-176', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 177', '21-cfr-part-177', 'Indirect Food Additives: Polymers', 'https://www.ecfr.gov/current/title-21/part-177', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 178', '21-cfr-part-178', 'Indirect Food Additives: Adjuvants, Production Aids, and Sanitizers', 'https://www.ecfr.gov/current/title-21/part-178', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 179', '21-cfr-part-179', 'Irradiation in the Production, Processing and Handling of Food', 'https://www.ecfr.gov/current/title-21/part-179', '{"food-safety","drugs","radiation"}'::text[]),
    ('21 CFR Part 180', '21-cfr-part-180', 'Food Additives Permitted in Food or in Contact with Food on an Interim Basis Pending Additional Study', 'https://www.ecfr.gov/current/title-21/part-180', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 181', '21-cfr-part-181', 'Prior-Sanctioned Food Ingredients', 'https://www.ecfr.gov/current/title-21/part-181', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 182', '21-cfr-part-182', 'Substances Generally Recognized as Safe', 'https://www.ecfr.gov/current/title-21/part-182', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 184', '21-cfr-part-184', 'Direct Food Substances Affirmed as Generally Recognized as Safe', 'https://www.ecfr.gov/current/title-21/part-184', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 186', '21-cfr-part-186', 'Indirect Food Substances Affirmed as Generally Recognized as Safe', 'https://www.ecfr.gov/current/title-21/part-186', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 189', '21-cfr-part-189', 'Substances Prohibited from Use in Human Food', 'https://www.ecfr.gov/current/title-21/part-189', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 190', '21-cfr-part-190', 'Dietary Supplements', 'https://www.ecfr.gov/current/title-21/part-190', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 200', '21-cfr-part-200', 'General', 'https://www.ecfr.gov/current/title-21/part-200', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 201', '21-cfr-part-201', 'Labeling', 'https://www.ecfr.gov/current/title-21/part-201', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 202', '21-cfr-part-202', 'Prescription Drug Advertising', 'https://www.ecfr.gov/current/title-21/part-202', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 203', '21-cfr-part-203', 'Prescription Drug Marketing', 'https://www.ecfr.gov/current/title-21/part-203', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 205', '21-cfr-part-205', 'Guidelines for State Licensing of Wholesale Prescription Drug Distributors', 'https://www.ecfr.gov/current/title-21/part-205', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 206', '21-cfr-part-206', 'Imprinting of Solid Oral Dosage Form Drug Products for Human Use', 'https://www.ecfr.gov/current/title-21/part-206', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 207', '21-cfr-part-207', 'Requirements for Foreign and Domestic Establishment Registration and Listing for Human Drugs, Including Drugs That Are Regulated Under a Biologics License Application, and Animal Drugs, and the National Drug Code', 'https://www.ecfr.gov/current/title-21/part-207', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 208', '21-cfr-part-208', 'Medication Guides for Prescription Drug Products', 'https://www.ecfr.gov/current/title-21/part-208', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 209', '21-cfr-part-209', 'Requirement for Authorized Dispensers and Pharmacies to Distribute a Side Effects Statement', 'https://www.ecfr.gov/current/title-21/part-209', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 210', '21-cfr-part-210', 'Current Good Manufacturing Practice in Manufacturing, Processing, Packing, or Holding of Drugs; General', 'https://www.ecfr.gov/current/title-21/part-210', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 211', '21-cfr-part-211', 'Current Good Manufacturing Practice for Finished Pharmaceuticals', 'https://www.ecfr.gov/current/title-21/part-211', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 212', '21-cfr-part-212', 'Current Good Manufacturing Practice for Positron Emission Tomography Drugs', 'https://www.ecfr.gov/current/title-21/part-212', '{"emissions","food-safety","drugs"}'::text[]),
    ('21 CFR Part 213', '21-cfr-part-213', 'Current Good Manufacturing Practice for Medical Gases', 'https://www.ecfr.gov/current/title-21/part-213', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 216', '21-cfr-part-216', 'Human Drug Compounding', 'https://www.ecfr.gov/current/title-21/part-216', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 225', '21-cfr-part-225', 'Current Good Manufacturing Practice for Medicated Feeds', 'https://www.ecfr.gov/current/title-21/part-225', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 226', '21-cfr-part-226', 'Current Good Manufacturing Practice for Type a Medicated Articles', 'https://www.ecfr.gov/current/title-21/part-226', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 230', '21-cfr-part-230', 'Certification and Postmarketing Reporting for Designated Medical Gases', 'https://www.ecfr.gov/current/title-21/part-230', '{"permitting","reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 250', '21-cfr-part-250', 'Special Requirements for Specific Human Drugs', 'https://www.ecfr.gov/current/title-21/part-250', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 251', '21-cfr-part-251', 'Section 804 Importation Program', 'https://www.ecfr.gov/current/title-21/part-251', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 290', '21-cfr-part-290', 'Controlled Drugs', 'https://www.ecfr.gov/current/title-21/part-290', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 299', '21-cfr-part-299', 'Drugs; Official Names and Established Names', 'https://www.ecfr.gov/current/title-21/part-299', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 300', '21-cfr-part-300', 'General', 'https://www.ecfr.gov/current/title-21/part-300', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 310', '21-cfr-part-310', 'New Drugs', 'https://www.ecfr.gov/current/title-21/part-310', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 312', '21-cfr-part-312', 'Investigational New Drug Application', 'https://www.ecfr.gov/current/title-21/part-312', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 314', '21-cfr-part-314', 'Applications for FDA Approval to Market a New Drug', 'https://www.ecfr.gov/current/title-21/part-314', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 315', '21-cfr-part-315', 'Diagnostic Radiopharmaceuticals', 'https://www.ecfr.gov/current/title-21/part-315', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 316', '21-cfr-part-316', 'Orphan Drugs', 'https://www.ecfr.gov/current/title-21/part-316', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 317', '21-cfr-part-317', 'Qualifying Pathogens', 'https://www.ecfr.gov/current/title-21/part-317', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 320', '21-cfr-part-320', 'Bioavailability and Bioequivalence Requirements', 'https://www.ecfr.gov/current/title-21/part-320', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 328', '21-cfr-part-328', 'Over-the-Counter Drug Products Intended for Oral Ingestion That Contain Alcohol', 'https://www.ecfr.gov/current/title-21/part-328', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 329', '21-cfr-part-329', 'Nonprescription Human Drug Products Subject to Section 760 of the Federal Food, Drug, and Cosmetic Act', 'https://www.ecfr.gov/current/title-21/part-329', '{"food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 330', '21-cfr-part-330', 'Over-the-Counter (OTC) Human Drugs Which Are Generally Recognized as Safe and Effective and Not Misbranded', 'https://www.ecfr.gov/current/title-21/part-330', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 331', '21-cfr-part-331', 'Antacid Products for Over-the-Counter (OTC) Human Use', 'https://www.ecfr.gov/current/title-21/part-331', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 332', '21-cfr-part-332', 'Antiflatulent Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-332', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 333', '21-cfr-part-333', 'Topical Antimicrobial Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-333', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 335', '21-cfr-part-335', 'Antidiarrheal Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-335', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 336', '21-cfr-part-336', 'Antiemetic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-336', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 338', '21-cfr-part-338', 'Nighttime Sleep-Aid Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-338', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 340', '21-cfr-part-340', 'Stimulant Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-340', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 341', '21-cfr-part-341', 'Cold, Cough, Allergy, Bronchodilator, and Antiasthmatic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-341', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 343', '21-cfr-part-343', 'Internal Analgesic, Antipyretic, and Antirheumatic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-343', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 344', '21-cfr-part-344', 'Topical Otic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-344', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 346', '21-cfr-part-346', 'Anorectal Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-346', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 347', '21-cfr-part-347', 'Skin Protectant Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-347', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 348', '21-cfr-part-348', 'External Analgesic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-348', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 349', '21-cfr-part-349', 'Ophthalmic Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-349', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 350', '21-cfr-part-350', 'Antiperspirant Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-350', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 352', '21-cfr-part-352', 'Sunscreen Drug Products for Over-the-Counter Human Use [Stayed Indefinitely]', 'https://www.ecfr.gov/current/title-21/part-352', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 355', '21-cfr-part-355', 'Anticaries Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-355', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 357', '21-cfr-part-357', 'Miscellaneous Internal Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-357', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 358', '21-cfr-part-358', 'Miscellaneous External Drug Products for Over-the-Counter Human Use', 'https://www.ecfr.gov/current/title-21/part-358', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 361', '21-cfr-part-361', 'Prescription Drugs for Human Use Generally Recognized as Safe and Effective and Not Misbranded: Drugs Used in Research', 'https://www.ecfr.gov/current/title-21/part-361', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 369', '21-cfr-part-369', 'Interpretative Statements Re Warnings on Drugs and Devices for Over-the-Counter Sale', 'https://www.ecfr.gov/current/title-21/part-369', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 500', '21-cfr-part-500', 'General', 'https://www.ecfr.gov/current/title-21/part-500', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 501', '21-cfr-part-501', 'Animal Food Labeling', 'https://www.ecfr.gov/current/title-21/part-501', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 502', '21-cfr-part-502', 'Common or Usual Names for Nonstandardized Animal Foods', 'https://www.ecfr.gov/current/title-21/part-502', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 507', '21-cfr-part-507', 'Current Good Manufacturing Practice, Hazard Analysis, and Risk-Based Preventive Controls for Food for Animals', 'https://www.ecfr.gov/current/title-21/part-507', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 509', '21-cfr-part-509', 'Unavoidable Contaminants in Animal Food and Food-Packaging Material', 'https://www.ecfr.gov/current/title-21/part-509', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 510', '21-cfr-part-510', 'New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-510', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 511', '21-cfr-part-511', 'New Animal Drugs for Investigational Use', 'https://www.ecfr.gov/current/title-21/part-511', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 514', '21-cfr-part-514', 'New Animal Drug Applications', 'https://www.ecfr.gov/current/title-21/part-514', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 515', '21-cfr-part-515', 'Medicated Feed Mill License', 'https://www.ecfr.gov/current/title-21/part-515', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 516', '21-cfr-part-516', 'New Animal Drugs for Minor Use and Minor Species', 'https://www.ecfr.gov/current/title-21/part-516', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 520', '21-cfr-part-520', 'Oral Dosage Form New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-520', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 522', '21-cfr-part-522', 'Implantation or Injectable Dosage Form New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-522', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 524', '21-cfr-part-524', 'Ophthalmic and Topical Dosage Form New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-524', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 526', '21-cfr-part-526', 'Intramammary Dosage Form New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-526', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 528', '21-cfr-part-528', 'Intentional Genomic Alterations in Animals', 'https://www.ecfr.gov/current/title-21/part-528', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 529', '21-cfr-part-529', 'Certain Other Dosage Form New Animal Drugs', 'https://www.ecfr.gov/current/title-21/part-529', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 530', '21-cfr-part-530', 'Extralabel Drug Use in Animals', 'https://www.ecfr.gov/current/title-21/part-530', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 556', '21-cfr-part-556', 'Tolerances for Residues of New Animal Drugs in Food', 'https://www.ecfr.gov/current/title-21/part-556', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 558', '21-cfr-part-558', 'New Animal Drugs for Use in Animal Feeds', 'https://www.ecfr.gov/current/title-21/part-558', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 570', '21-cfr-part-570', 'Food Additives', 'https://www.ecfr.gov/current/title-21/part-570', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 571', '21-cfr-part-571', 'Food Additive Petitions', 'https://www.ecfr.gov/current/title-21/part-571', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 573', '21-cfr-part-573', 'Food Additives Permitted in Feed and Drinking Water of Animals', 'https://www.ecfr.gov/current/title-21/part-573', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 579', '21-cfr-part-579', 'Irradiation in the Production, Processing, and Handling of Animal Feed and Pet Food', 'https://www.ecfr.gov/current/title-21/part-579', '{"food-safety","drugs","radiation"}'::text[]),
    ('21 CFR Part 582', '21-cfr-part-582', 'Substances Generally Recognized as Safe', 'https://www.ecfr.gov/current/title-21/part-582', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 584', '21-cfr-part-584', 'Food Substances Affirmed as Generally Recognized as Safe in Feed and Drinking Water of Animals', 'https://www.ecfr.gov/current/title-21/part-584', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 589', '21-cfr-part-589', 'Substances Prohibited from Use in Animal Food or Feed', 'https://www.ecfr.gov/current/title-21/part-589', '{"food-safety","drugs","chemicals"}'::text[]),
    ('21 CFR Part 600', '21-cfr-part-600', 'Biological Products: General', 'https://www.ecfr.gov/current/title-21/part-600', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 601', '21-cfr-part-601', 'Licensing', 'https://www.ecfr.gov/current/title-21/part-601', '{"permitting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 606', '21-cfr-part-606', 'Current Good Manufacturing Practice for Blood and Blood Components', 'https://www.ecfr.gov/current/title-21/part-606', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 607', '21-cfr-part-607', 'Establishment Registration and Product Listing for Manufacturers of Human Blood and Blood Products and Licensed Devices', 'https://www.ecfr.gov/current/title-21/part-607', '{"permitting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 610', '21-cfr-part-610', 'General Biological Products Standards', 'https://www.ecfr.gov/current/title-21/part-610', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 630', '21-cfr-part-630', 'Requirements for Blood and Blood Components Intended for Transfusion or for Further Manufacturing Use', 'https://www.ecfr.gov/current/title-21/part-630', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 640', '21-cfr-part-640', 'Additional Standards for Human Blood and Blood Products', 'https://www.ecfr.gov/current/title-21/part-640', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 660', '21-cfr-part-660', 'Additional Standards for Diagnostic Substances for Laboratory Tests', 'https://www.ecfr.gov/current/title-21/part-660', '{"food-safety","drugs","medical-devices","chemicals"}'::text[]),
    ('21 CFR Part 680', '21-cfr-part-680', 'Additional Standards for Miscellaneous Products', 'https://www.ecfr.gov/current/title-21/part-680', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 700', '21-cfr-part-700', 'General', 'https://www.ecfr.gov/current/title-21/part-700', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 701', '21-cfr-part-701', 'Cosmetic Labeling', 'https://www.ecfr.gov/current/title-21/part-701', '{"food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 710', '21-cfr-part-710', 'Voluntary Registration of Cosmetic Product Establishments', 'https://www.ecfr.gov/current/title-21/part-710', '{"permitting","food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 720', '21-cfr-part-720', 'Voluntary Filing of Cosmetic Product Ingredient Composition Statements', 'https://www.ecfr.gov/current/title-21/part-720', '{"reporting","food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 740', '21-cfr-part-740', 'Cosmetic Product Warning Statements', 'https://www.ecfr.gov/current/title-21/part-740', '{"food-safety","drugs","cosmetics"}'::text[]),
    ('21 CFR Part 800', '21-cfr-part-800', 'General', 'https://www.ecfr.gov/current/title-21/part-800', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 801', '21-cfr-part-801', 'Labeling', 'https://www.ecfr.gov/current/title-21/part-801', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 803', '21-cfr-part-803', 'Medical Device Reporting', 'https://www.ecfr.gov/current/title-21/part-803', '{"reporting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 806', '21-cfr-part-806', 'Medical Devices; Reports of Corrections and Removals', 'https://www.ecfr.gov/current/title-21/part-806', '{"reporting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 807', '21-cfr-part-807', 'Establishment Registration and Device Listing for Manufacturers and Initial Importers of Devices', 'https://www.ecfr.gov/current/title-21/part-807', '{"permitting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 808', '21-cfr-part-808', 'Exemptions from Federal Preemption of State and Local Medical Device Requirements', 'https://www.ecfr.gov/current/title-21/part-808', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 809', '21-cfr-part-809', 'In Vitro Diagnostic Products for Human Use', 'https://www.ecfr.gov/current/title-21/part-809', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 810', '21-cfr-part-810', 'Medical Device Recall Authority', 'https://www.ecfr.gov/current/title-21/part-810', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 812', '21-cfr-part-812', 'Investigational Device Exemptions', 'https://www.ecfr.gov/current/title-21/part-812', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 814', '21-cfr-part-814', 'Premarket Approval of Medical Devices', 'https://www.ecfr.gov/current/title-21/part-814', '{"permitting","food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 820', '21-cfr-part-820', 'Quality Management System Regulation', 'https://www.ecfr.gov/current/title-21/part-820', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 821', '21-cfr-part-821', 'Medical Device Tracking Requirements', 'https://www.ecfr.gov/current/title-21/part-821', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 822', '21-cfr-part-822', 'Postmarket Surveillance', 'https://www.ecfr.gov/current/title-21/part-822', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 830', '21-cfr-part-830', 'Unique Device Identification', 'https://www.ecfr.gov/current/title-21/part-830', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 860', '21-cfr-part-860', 'Medical Device Classification Procedures', 'https://www.ecfr.gov/current/title-21/part-860', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 861', '21-cfr-part-861', 'Procedures for Performance Standards Development', 'https://www.ecfr.gov/current/title-21/part-861', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 862', '21-cfr-part-862', 'Clinical Chemistry and Clinical Toxicology Devices', 'https://www.ecfr.gov/current/title-21/part-862', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 864', '21-cfr-part-864', 'Hematology and Pathology Devices', 'https://www.ecfr.gov/current/title-21/part-864', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 866', '21-cfr-part-866', 'Immunology and Microbiology Devices', 'https://www.ecfr.gov/current/title-21/part-866', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 868', '21-cfr-part-868', 'Anesthesiology Devices', 'https://www.ecfr.gov/current/title-21/part-868', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 870', '21-cfr-part-870', 'Cardiovascular Devices', 'https://www.ecfr.gov/current/title-21/part-870', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 872', '21-cfr-part-872', 'Dental Devices', 'https://www.ecfr.gov/current/title-21/part-872', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 874', '21-cfr-part-874', 'Ear, Nose, and Throat Devices', 'https://www.ecfr.gov/current/title-21/part-874', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 876', '21-cfr-part-876', 'Gastroenterology-Urology Devices', 'https://www.ecfr.gov/current/title-21/part-876', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 878', '21-cfr-part-878', 'General and Plastic Surgery Devices', 'https://www.ecfr.gov/current/title-21/part-878', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 880', '21-cfr-part-880', 'General Hospital and Personal Use Devices', 'https://www.ecfr.gov/current/title-21/part-880', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 882', '21-cfr-part-882', 'Neurological Devices', 'https://www.ecfr.gov/current/title-21/part-882', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 884', '21-cfr-part-884', 'Obstetrical and Gynecological Devices', 'https://www.ecfr.gov/current/title-21/part-884', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 886', '21-cfr-part-886', 'Ophthalmic Devices', 'https://www.ecfr.gov/current/title-21/part-886', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 888', '21-cfr-part-888', 'Orthopedic Devices', 'https://www.ecfr.gov/current/title-21/part-888', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 890', '21-cfr-part-890', 'Physical Medicine Devices', 'https://www.ecfr.gov/current/title-21/part-890', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 892', '21-cfr-part-892', 'Radiology Devices', 'https://www.ecfr.gov/current/title-21/part-892', '{"food-safety","drugs","medical-devices","radiation"}'::text[]),
    ('21 CFR Part 895', '21-cfr-part-895', 'Banned Devices', 'https://www.ecfr.gov/current/title-21/part-895', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 898', '21-cfr-part-898', 'Performance Standard for Electrode Lead Wires and Patient Cables', 'https://www.ecfr.gov/current/title-21/part-898', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 900', '21-cfr-part-900', 'Mammography', 'https://www.ecfr.gov/current/title-21/part-900', '{"food-safety","drugs","medical-devices"}'::text[]),
    ('21 CFR Part 1000', '21-cfr-part-1000', 'General', 'https://www.ecfr.gov/current/title-21/part-1000', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1002', '21-cfr-part-1002', 'Records and Reports', 'https://www.ecfr.gov/current/title-21/part-1002', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 1003', '21-cfr-part-1003', 'Notification of Defects or Failure to Comply', 'https://www.ecfr.gov/current/title-21/part-1003', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1004', '21-cfr-part-1004', 'Repurchase, Repairs, or Replacement of Electronic Products', 'https://www.ecfr.gov/current/title-21/part-1004', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1005', '21-cfr-part-1005', 'Importation of Electronic Products', 'https://www.ecfr.gov/current/title-21/part-1005', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1010', '21-cfr-part-1010', 'Performance Standards for Electronic Products: General', 'https://www.ecfr.gov/current/title-21/part-1010', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1020', '21-cfr-part-1020', 'Performance Standards for Ionizing Radiation Emitting Products', 'https://www.ecfr.gov/current/title-21/part-1020', '{"food-safety","drugs","radiation"}'::text[]),
    ('21 CFR Part 1030', '21-cfr-part-1030', 'Performance Standards for Microwave and Radio Frequency Emitting Products', 'https://www.ecfr.gov/current/title-21/part-1030', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1040', '21-cfr-part-1040', 'Performance Standards for Light-Emitting Products', 'https://www.ecfr.gov/current/title-21/part-1040', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1100', '21-cfr-part-1100', 'General', 'https://www.ecfr.gov/current/title-21/part-1100', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1105', '21-cfr-part-1105', 'General', 'https://www.ecfr.gov/current/title-21/part-1105', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1107', '21-cfr-part-1107', 'Exemption Requests and Substantial Equivalence Reports', 'https://www.ecfr.gov/current/title-21/part-1107', '{"reporting","food-safety","drugs"}'::text[]),
    ('21 CFR Part 1114', '21-cfr-part-1114', 'Premarket Tobacco Product Applications', 'https://www.ecfr.gov/current/title-21/part-1114', '{"permitting","food-safety","drugs","tobacco"}'::text[]),
    ('21 CFR Part 1140', '21-cfr-part-1140', 'Cigarettes, Smokeless Tobacco, and Covered Tobacco Products', 'https://www.ecfr.gov/current/title-21/part-1140', '{"food-safety","drugs","tobacco"}'::text[]),
    ('21 CFR Part 1141', '21-cfr-part-1141', 'Required Warnings for Cigarette Packages and Advertisements', 'https://www.ecfr.gov/current/title-21/part-1141', '{"food-safety","drugs","tobacco"}'::text[]),
    ('21 CFR Part 1143', '21-cfr-part-1143', 'Minimum Required Warning Statements', 'https://www.ecfr.gov/current/title-21/part-1143', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1150', '21-cfr-part-1150', 'User Fees', 'https://www.ecfr.gov/current/title-21/part-1150', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1210', '21-cfr-part-1210', 'Regulations Under the Federal Import Milk Act', 'https://www.ecfr.gov/current/title-21/part-1210', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1230', '21-cfr-part-1230', 'Regulations Under the Federal Caustic Poison Act', 'https://www.ecfr.gov/current/title-21/part-1230', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1240', '21-cfr-part-1240', 'Control of Communicable Diseases', 'https://www.ecfr.gov/current/title-21/part-1240', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1250', '21-cfr-part-1250', 'Interstate Conveyance Sanitation', 'https://www.ecfr.gov/current/title-21/part-1250', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1271', '21-cfr-part-1271', 'Human Cells, Tissues, and Cellular and Tissue-Based Products', 'https://www.ecfr.gov/current/title-21/part-1271', '{"food-safety","drugs"}'::text[]),
    ('21 CFR Part 1300', '21-cfr-part-1300', 'Definitions', 'https://www.ecfr.gov/current/title-21/part-1300', '{"drugs"}'::text[]),
    ('21 CFR Part 1301', '21-cfr-part-1301', 'Registration of Manufacturers, Distributors, and Dispensers of Controlled Substances', 'https://www.ecfr.gov/current/title-21/part-1301', '{"permitting","drugs","chemicals"}'::text[]),
    ('21 CFR Part 1302', '21-cfr-part-1302', 'Labeling and Packaging Requirements for Controlled Substances', 'https://www.ecfr.gov/current/title-21/part-1302', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1303', '21-cfr-part-1303', 'Quotas', 'https://www.ecfr.gov/current/title-21/part-1303', '{"drugs"}'::text[]),
    ('21 CFR Part 1304', '21-cfr-part-1304', 'Records and Reports of Registrants', 'https://www.ecfr.gov/current/title-21/part-1304', '{"reporting","drugs"}'::text[]),
    ('21 CFR Part 1305', '21-cfr-part-1305', 'Orders for Schedule I and II Controlled Substances', 'https://www.ecfr.gov/current/title-21/part-1305', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1306', '21-cfr-part-1306', 'Prescriptions', 'https://www.ecfr.gov/current/title-21/part-1306', '{"drugs"}'::text[]),
    ('21 CFR Part 1307', '21-cfr-part-1307', 'Miscellaneous', 'https://www.ecfr.gov/current/title-21/part-1307', '{"drugs"}'::text[]),
    ('21 CFR Part 1308', '21-cfr-part-1308', 'Schedules of Controlled Substances', 'https://www.ecfr.gov/current/title-21/part-1308', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1309', '21-cfr-part-1309', 'Registration of Manufacturers, Distributors, Importers and Exporters of List I Chemicals', 'https://www.ecfr.gov/current/title-21/part-1309', '{"permitting","drugs","chemicals"}'::text[]),
    ('21 CFR Part 1310', '21-cfr-part-1310', 'Records and Reports of Listed Chemicals and Certain Machines; Importation and Exportation of Certain Machines', 'https://www.ecfr.gov/current/title-21/part-1310', '{"reporting","drugs","chemicals"}'::text[]),
    ('21 CFR Part 1311', '21-cfr-part-1311', 'Requirements for Electronic Orders and Prescriptions', 'https://www.ecfr.gov/current/title-21/part-1311', '{"drugs"}'::text[]),
    ('21 CFR Part 1312', '21-cfr-part-1312', 'Importation and Exportation of Controlled Substances', 'https://www.ecfr.gov/current/title-21/part-1312', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1313', '21-cfr-part-1313', 'Importation and Exportation of List I and List II Chemicals', 'https://www.ecfr.gov/current/title-21/part-1313', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1314', '21-cfr-part-1314', 'Retail Sale of Scheduled Listed Chemical Products', 'https://www.ecfr.gov/current/title-21/part-1314', '{"drugs","chemicals"}'::text[]),
    ('21 CFR Part 1315', '21-cfr-part-1315', 'Importation and Production Quotas for Ephedrine, Pseudoephedrine, and Phenylpropanolamine', 'https://www.ecfr.gov/current/title-21/part-1315', '{"drugs"}'::text[]),
    ('21 CFR Part 1316', '21-cfr-part-1316', 'Administrative Functions, Practices, and Procedures', 'https://www.ecfr.gov/current/title-21/part-1316', '{"drugs"}'::text[]),
    ('21 CFR Part 1317', '21-cfr-part-1317', 'Disposal', 'https://www.ecfr.gov/current/title-21/part-1317', '{"drugs"}'::text[]),
    ('21 CFR Part 1318', '21-cfr-part-1318', 'Controls to Satisfy the Requirements of the Act Applicable to the Manufacturing of Marihuana', 'https://www.ecfr.gov/current/title-21/part-1318', '{"drugs"}'::text[]),
    ('21 CFR Part 1321', '21-cfr-part-1321', 'DEA Mailing Addresses', 'https://www.ecfr.gov/current/title-21/part-1321', '{"drugs"}'::text[]),
    ('21 CFR Part 1401', '21-cfr-part-1401', 'Public Availability of Information', 'https://www.ecfr.gov/current/title-21/part-1401', '{"reporting","drugs"}'::text[]),
    ('21 CFR Part 1402', '21-cfr-part-1402', 'Mandatory Declassification Review', 'https://www.ecfr.gov/current/title-21/part-1402', '{"drugs"}'::text[])
) as v(citation, slug, title, source_url, topics)
on conflict (regulator_id, citation) do update
  set title = excluded.title, slug = excluded.slug, source_url = excluded.source_url,
      topics = excluded.topics, last_changed_at = now();
