-- ===========================================================================
-- Vantage — CNSC REGDOC catalogue (baked snapshot)
-- ---------------------------------------------------------------------------
-- Durable seed of the Canadian Nuclear Safety Commission REGDOC catalogue,
-- generated from the public regulatory-documents index. Mirrors what the
-- cnsc-regulatory-documents connector upserts, so content exists even if the
-- live site changes or blocks. body_text is left null and filled by the
-- enrichment pass from each document's published HTML source_url.
--
--   64 REGDOCs across the 1.x / 2.x / 3.x series.
-- ===========================================================================

with cnsc as (select id from regwatch.regulators where slug = 'ca-cnsc')
insert into regwatch.regulatory_items
  (regulator_id, citation, slug, title, instrument_type, status, source_url, jurisdiction_code, topics)
select cnsc.id, v.citation, v.slug, v.title, v.instrument_type, v.status, v.source_url, 'CA', v.topics
from cnsc, (values
    ('REGDOC-1.1.1', 'regdoc-1-1-1', 'Site Evaluation and Site Preparation for New Reactor Facilities, Version 1.3', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-1-1-v1-3/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.1.2', 'regdoc-1-1-2', 'Licence Application Guide: Licence to Construct A Reactor Facility, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-1-2-v2/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.1.3', 'regdoc-1-1-3', 'Licence Application Guide: Licence to operate a Nuclear Power Plant, Version 1.3', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-1-3-v1-3/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.1.5', 'regdoc-1-1-5', 'Supplemental Information for Small Modular Reactor Proponents, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-1-5-v1-1/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.2.1', 'regdoc-1-2-1', 'Guidance on Deep Geological Repository Site Characterization', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-2-1/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.2.2', 'regdoc-1-2-2', 'Licence Application Guide: Class IB Processing Facilities', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-2-2/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.2.3', 'regdoc-1-2-3', 'Licence Application Guide: Licence to prepare Site for a Deep Geological Repository', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-2-3/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.4.1', 'regdoc-1-4-1', 'Licence Application Guide: Class II Nuclear Facilities and Prescribed Equipment, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-4-1-v1-1/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-1.5.1', 'regdoc-1-5-1', 'Application Guide: Certification of Radiation Devices or Class II Prescribed Equipment, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-5-1-v1-1/', '{"nuclear","radiation","permitting"}'::text[]),
    ('REGDOC-1.6.1', 'regdoc-1-6-1', 'Licence Application Guide: Nuclear Substances and Radiation Devices, Version 2.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-6-1-v2-1/', '{"nuclear","radiation","permitting"}'::text[]),
    ('REGDOC-1.6.2', 'regdoc-1-6-2', 'Radiation Protection Programs for Nuclear Substances and Radiation Devices Licences', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc1-6-2/', '{"nuclear","radiation","permitting"}'::text[]),
    ('REGDOC-2.1.1', 'regdoc-2-1-1', 'Management System', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-1-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.1.2', 'regdoc-2-1-2', 'Safety Culture', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-1-2/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.2.1', 'regdoc-2-2-1', 'Human Performance, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-2-1-v2/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.2.2', 'regdoc-2-2-2', 'Personnel Training, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-2-2-v2/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.2.3', 'regdoc-2-2-3', 'Personnel Certification: Radiation Safety Officers', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-2-3/', '{"nuclear","radiation","process-safety","permitting"}'::text[]),
    ('REGDOC-2.2.4', 'regdoc-2-2-4', 'Fitness for Duty: Managing Worker Fatigue', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-2-4/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.2.5', 'regdoc-2-2-5', 'Minimum Staff Complement', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-2-5/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.3.1', 'regdoc-2-3-1', 'Conduct of Licensed Activities: Construction and Commissioning Programs', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-3-1/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.3.2', 'regdoc-2-3-2', 'Accident Management, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-3-2v2/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.3.3', 'regdoc-2-3-3', 'Periodic Safety Reviews', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-3-3/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.3.4', 'regdoc-2-3-4', 'Operations Programs for Reactor Facilities', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-3-4/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.4.1', 'regdoc-2-4-1', 'Deterministic Safety Analysis', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-4-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.4.2', 'regdoc-2-4-2', 'Probabilistic Safety Assessment (PSA) for Reactor Facilities, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-4-2-v2/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.4.3', 'regdoc-2-4-3', 'Nuclear Criticality Safety, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-4-3-v1-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.4.4', 'regdoc-2-4-4', 'Safety Analysis for Class IB Nuclear Facilities', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-4-4/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.4.5', 'regdoc-2-4-5', 'Nuclear Fuel Safety', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-4-5/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.5.1', 'regdoc-2-5-1', 'General Design Considerations: Human Factors', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.5.2', 'regdoc-2-5-2', 'Design of Reactor Facilities, Version 2.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-2-v2-1/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.5.4', 'regdoc-2-5-4', 'Design of Uranium Mines and Mills: Ventilation Systems, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-4-v1-1/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.5.5', 'regdoc-2-5-5', 'Design of Industrial Radiography Installations', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-5/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.5.6', 'regdoc-2-5-6', 'Design of Rooms Where Unsealed Nuclear Substances Are Used', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-6/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.5.7', 'regdoc-2-5-7', 'Design, Testing and Performance of Exposure Devices, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-5-7-v1-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.6.1', 'regdoc-2-6-1', 'Reliability Programs for Nuclear Power Plants', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-6-1/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.6.2', 'regdoc-2-6-2', 'Maintenance Programs for Nuclear Power Plants', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-6-2/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.6.3', 'regdoc-2-6-3', 'Aging Management', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-6-3/', '{"nuclear","process-safety"}'::text[]),
    ('REGDOC-2.6.4', 'regdoc-2-6-4', 'Chemistry Control for Reactor Facilities', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-6-4-draft/', '{"nuclear","process-safety","permitting"}'::text[]),
    ('REGDOC-2.7.1', 'regdoc-2-7-1', 'Radiation Protection, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-7-1v1-1/', '{"nuclear","radiation"}'::text[]),
    ('REGDOC-2.7.2', 'regdoc-2-7-2', 'Dosimetry, Volume I: Ascertaining Occupational Dose', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-7-2-vol-i/', '{"nuclear","radiation"}'::text[]),
    ('REGDOC-2.7.3', 'regdoc-2-7-3', 'Radiation Protection Guidelines for the Safe Handling of Decedents', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-7-3/', '{"nuclear","radiation"}'::text[]),
    ('REGDOC-2.8.1', 'regdoc-2-8-1', 'Conventional Health and Safety', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-8-1/', '{"nuclear","worker-safety","radiation"}'::text[]),
    ('REGDOC-2.9.1', 'regdoc-2-9-1', 'Environmental Principles, Assessments and Protection Measures, Version 1.2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-9-1-vol1-2/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.9.2', 'regdoc-2-9-2', 'Controlling Releases to the Environment', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-9-2/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.10.1', 'regdoc-2-10-1', 'Nuclear Emergency Preparedness and Response, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-10-1v2/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.11', 'regdoc-2-11', 'Framework for Radioactive Waste Management and Decommissioning in Canada, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-11-v2/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.11.1', 'regdoc-2-11-1', 'Waste Management, Volume I: Management of Radioactive Waste', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-11-1-vol1/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.11.2', 'regdoc-2-11-2', 'Decommissioning', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-11-2/', '{"nuclear","emissions"}'::text[]),
    ('REGDOC-2.12.2', 'regdoc-2-12-2', 'Site Access Security Clearance', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-12-2/', '{"nuclear"}'::text[]),
    ('REGDOC-2.12.3', 'regdoc-2-12-3', 'Security of Nuclear Substances: Sealed Sources and Category I, II and III Nuclear Material, Version 2.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-12-3-v2-1/', '{"nuclear"}'::text[]),
    ('REGDOC-2.13.1', 'regdoc-2-13-1', 'Safeguards and Nuclear Material Accountancy', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-13-1/', '{"nuclear"}'::text[]),
    ('REGDOC-2.13.2', 'regdoc-2-13-2', 'Import and Export, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-13-2-ver2/', '{"nuclear"}'::text[]),
    ('REGDOC-2.14.1', 'regdoc-2-14-1', 'Information Incorporated by Reference in Canada’s Packaging and Transport of Nuclear Substances Regulations, 2015, Volume I, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc2-14-1-v2-2020/', '{"nuclear"}'::text[]),
    ('REGDOC-3.1.1', 'regdoc-3-1-1', 'Reporting Requirements for Nuclear Power Plants, Version 3', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-1-1-v3/', '{"nuclear","reporting"}'::text[]),
    ('REGDOC-3.1.2', 'regdoc-3-1-2', 'Reporting Requirements, Volume I: Non-Power Reactor Class I Facilities and Uranium Mines and Mills, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-1-2-v1-1/', '{"nuclear","permitting","reporting"}'::text[]),
    ('REGDOC-3.1.3', 'regdoc-3-1-3', 'Reporting Requirements for Waste Nuclear Substance Licensees, Class II Nuclear Facilities and Users of Prescribed Equipment, Nuclear Substances and Radiation Devices', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-1-3/', '{"nuclear","radiation","emissions","permitting","reporting"}'::text[]),
    ('REGDOC-3.2.1', 'regdoc-3-2-1', 'Public Information and Disclosure', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-2-1/', '{"nuclear"}'::text[]),
    ('REGDOC-3.2.2', 'regdoc-3-2-2', 'Indigenous Engagement, Version 1.2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-2-2-v1-2/', '{"nuclear"}'::text[]),
    ('REGDOC-3.3.1', 'regdoc-3-3-1', 'Financial Guarantees for Decommissioning of Nuclear Facilities and Termination of Licensed Activities', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-3-1/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-3.4.1', 'regdoc-3-4-1', 'Guide for Applicants and Intervenors Writing CNSC Commission Member Documents, Version 1.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-4-1-v1-1/', '{"nuclear"}'::text[]),
    ('REGDOC-3.5.1', 'regdoc-3-5-1', 'Information Dissemination: Licensing Process for Class I Nuclear Facilities and Uranium Mines and Mills, Version 2.1', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-5-1-v2-1/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-3.5.2', 'regdoc-3-5-2', 'Compliance and Enforcement: Administrative Monetary Penalties, Version 2', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-5-2/', '{"nuclear"}'::text[]),
    ('REGDOC-3.5.3', 'regdoc-3-5-3', 'Regulatory Fundamentals, Version 3', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-5-3-v3/', '{"nuclear"}'::text[]),
    ('REGDOC-3.5.4', 'regdoc-3-5-4', 'Pre-licensing Review of a Vendor’s Reactor Design', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-5-4/', '{"nuclear","permitting"}'::text[]),
    ('REGDOC-3.6', 'regdoc-3-6', 'Glossary of CNSC Terminology', 'guidance', 'in-force', 'https://www.cnsc-ccsn.gc.ca/eng/acts-and-regulations/regulatory-documents/published/html/regdoc3-6/', '{"nuclear"}'::text[])
) as v(citation, slug, title, instrument_type, status, source_url, topics)
on conflict (regulator_id, citation) do update
  set title = excluded.title,
      slug = excluded.slug,
      instrument_type = excluded.instrument_type,
      status = excluded.status,
      source_url = excluded.source_url,
      topics = excluded.topics,
      last_changed_at = now();
