-- ===========================================================================
-- Vantage — SASO regulation seed items (fixed — replaces 20260705)
-- ---------------------------------------------------------------------------
-- 20260705 cast values as regwatch.instrument_type and regwatch.item_status,
-- but those aren't Postgres enum types — the schema stores both as plain
-- `text` with inline-comment value lists (see 20260602_regwatch_initial.sql
-- line 78-79). This rewrite drops the bad casts. Otherwise identical to
-- 20260705 and idempotent on (regulator_id, citation).
-- ===========================================================================

-- Ensure SASO regulator exists (no-op if 20260703 already ran).
insert into regwatch.regulators
  (slug, name, short_name, jurisdiction_code, jurisdiction_name, region, regulator_type, canonical_url, description, topic_domains)
values
  ('sa-saso',
   'Saudi Standards, Metrology and Quality Organization',
   'SASO',
   'SA',
   'Saudi Arabia',
   'mea',
   'standards-body',
   'https://www.saso.gov.sa',
   'National standards body for the Kingdom of Saudi Arabia — issues technical regulations, mandatory and voluntary standards, GSO-aligned conformity requirements across food, chemicals, energy, electronics, vehicles, toys, cosmetics, and construction materials.',
   '{standards,gulf,gcc-alignment,energy,chemicals,worker-safety}'::text[])
on conflict (slug) do nothing;

with saso as (
  select id from regwatch.regulators where slug = 'sa-saso'
)
insert into regwatch.regulatory_items
  (regulator_id, citation, slug, title, instrument_type, status,
   effective_date, published_at, last_changed_at, source_url,
   summary, jurisdiction_code, topics, enrichment_status)
select
  saso.id,
  v.citation,
  v.slug,
  v.title,
  v.instrument_type,         -- plain text, no cast
  v.status,                  -- plain text, no cast
  v.effective_date::date,
  v.published_at::timestamptz,
  v.last_changed_at::timestamptz,
  v.source_url,
  v.summary,
  'SA',
  v.topics::text[],
  'pending'
from saso, (values
  ('SASO 2870', 'saso-2870',
   'Energy labelling and minimum efficiency for room air conditioners',
   'standard', 'in-force', '2018-01-01', '2017-09-15', '2024-03-10',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2870.aspx',
   'Mandatory energy efficiency labelling and minimum energy performance standards for split, window, and packaged air conditioners up to 65 kW cooling capacity sold in Saudi Arabia.',
   '{standards,energy,gcc-alignment}'),
  ('SASO 2483', 'saso-2483',
   'Energy labelling and minimum efficiency for household refrigerators and freezers',
   'standard', 'in-force', '2019-01-01', '2018-07-01', '2023-11-22',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2483.aspx',
   'MEPS + label for household refrigerator-freezers, freezers, and wine coolers ≤1500L. Includes star-rating display and bilingual Arabic-English label format.',
   '{standards,energy,gcc-alignment}'),
  ('SASO 2884', 'saso-2884',
   'Energy efficiency standards for clothes washing machines',
   'standard', 'in-force', '2019-06-01', '2019-02-15', '2024-05-20',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2884.aspx',
   'Mandatory energy efficiency labelling for top-loading and front-loading washing machines up to 12 kg load capacity.',
   '{standards,energy}'),
  ('SASO 2902', 'saso-2902',
   'Safety requirements for toys — Mechanical and physical properties',
   'standard', 'in-force', '2020-01-01', '2019-08-10', '2024-01-12',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2902.aspx',
   'Mechanical and physical safety requirements for toys imported into or manufactured in the Kingdom; covers small parts, sharp edges, projectiles, magnets, sound levels. Aligned with EN 71-1.',
   '{standards,worker-safety}'),
  ('SASO 2530', 'saso-2530',
   'Vehicle tyres — Specifications and test methods',
   'standard', 'in-force', '2018-07-01', '2017-12-04', '2023-08-30',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2530.aspx',
   'Performance, dimensional and marking requirements for new passenger-car, light-truck, and heavy-duty tyres sold in Saudi Arabia. Includes desert-temperature endurance tests.',
   '{standards,gcc-alignment}'),
  ('SASO 2078', 'saso-2078',
   'Petroleum products — Unleaded gasoline for motor vehicles',
   'standard', 'in-force', '2017-09-01', '2017-04-15', '2024-09-05',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2078.aspx',
   'Specifications for 91-octane and 95-octane unleaded gasoline at retail. Sulphur cap of 10 ppm phased in 2023.',
   '{standards,energy,emissions}'),
  ('SASO 666', 'saso-666',
   'Automotive diesel fuel — Specifications',
   'standard', 'in-force', '2017-09-01', '2017-04-15', '2024-09-05',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-666.aspx',
   'Specifications for automotive diesel fuel — cetane number, density, sulphur cap (10 ppm for road use 2024), cold-flow properties for KSA climate range.',
   '{standards,energy,emissions}'),
  ('SASO 1463', 'saso-1463',
   'Motor vehicles — Vehicle Identification Number (VIN) requirements',
   'standard', 'in-force', '2014-06-01', '2014-01-20', '2022-04-12',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-1463.aspx',
   'VIN format, location, and durability requirements for all motor vehicles registered in Saudi Arabia. Aligned with ISO 3779.',
   '{standards,gcc-alignment}'),
  ('SASO IEC 60335-1', 'saso-iec-60335-1',
   'Safety of household and similar electrical appliances — General requirements',
   'standard', 'in-force', '2016-01-01', '2015-06-30', '2023-12-18',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-IEC-60335-1.aspx',
   'Adoption of IEC 60335-1 as a Saudi mandatory standard. Covers insulation, leakage current, mechanical strength, and EMC requirements for household appliances ≤ 250 V single phase / 480 V multi-phase.',
   '{standards,worker-safety}'),
  ('SASO IEC 62133', 'saso-iec-62133',
   'Safety requirements for lithium-ion batteries',
   'standard', 'in-force', '2020-03-01', '2019-11-08', '2024-02-14',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-IEC-62133.aspx',
   'Mandatory safety requirements for portable secondary cells and batteries containing alkaline or non-acid electrolytes — covers electronics and EV applications.',
   '{standards,chemicals}'),
  ('SASO 2885', 'saso-2885',
   'Mobile phone safety and SAR limits',
   'standard', 'in-force', '2018-11-01', '2018-05-12', '2023-09-25',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2885.aspx',
   'Mandatory Specific Absorption Rate (SAR) limits for mobile phones sold in Saudi Arabia. Maximum 2.0 W/kg averaged over 10 g of tissue.',
   '{standards}'),
  ('SASO 1055', 'saso-1055',
   'Bottled and packaged drinking water — Quality requirements',
   'standard', 'in-force', '2016-04-01', '2015-12-20', '2024-06-30',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-1055.aspx',
   'Physical, chemical and microbiological quality limits for bottled drinking water and packaged mineral water sold in Saudi Arabia.',
   '{standards}'),
  ('SASO 2233', 'saso-2233',
   'Cosmetics — Labelling and ingredient declaration requirements',
   'standard', 'in-force', '2019-05-01', '2018-10-15', '2024-04-08',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2233.aspx',
   'Mandatory labelling, ingredient declaration, and prohibited-substance list for cosmetic products sold in Saudi Arabia. Bilingual Arabic-English label.',
   '{standards,chemicals}'),
  ('SASO ISO 22000', 'saso-iso-22000',
   'Food safety management systems — Requirements',
   'standard', 'in-force', '2018-06-01', '2018-01-10', '2023-10-15',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-ISO-22000.aspx',
   'Saudi adoption of ISO 22000:2018 — requirements for any organisation in the food chain to demonstrate ability to control food safety hazards.',
   '{standards}'),
  ('SASO 14598', 'saso-14598',
   'Cosmetics — Microbiological limits',
   'standard', 'in-force', '2020-09-01', '2020-04-20', '2024-08-22',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-14598.aspx',
   'Microbiological quality limits for cosmetic products including baby cosmetics, eye-area products, and lip products.',
   '{standards,chemicals}'),
  ('SASO ISO 9001', 'saso-iso-9001',
   'Quality management systems — Requirements',
   'standard', 'in-force', '2016-09-15', '2016-03-01', '2023-07-11',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-ISO-9001.aspx',
   'Saudi adoption of ISO 9001:2015 — quality management system requirements applicable to any organisation, regardless of type, size, or product/service.',
   '{standards}'),
  ('SASO ISO 14001', 'saso-iso-14001',
   'Environmental management systems — Requirements',
   'standard', 'in-force', '2016-09-15', '2016-03-01', '2023-07-11',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-ISO-14001.aspx',
   'Saudi adoption of ISO 14001:2015 — environmental management system requirements with guidance for use.',
   '{standards,emissions}'),
  ('SASO ISO 45001', 'saso-iso-45001',
   'Occupational health and safety management systems — Requirements',
   'standard', 'in-force', '2019-03-12', '2018-12-01', '2024-01-30',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-ISO-45001.aspx',
   'Saudi adoption of ISO 45001:2018 — OH&S management system requirements with guidance for use.',
   '{standards,worker-safety}'),
  ('SASO 2725', 'saso-2725',
   'Building materials — Mandatory conformity assessment',
   'standard', 'in-force', '2019-01-15', '2018-08-22', '2024-05-15',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2725.aspx',
   'Mandatory conformity assessment requirements for cement, steel rebar, ready-mix concrete, and structural materials used in Saudi construction projects.',
   '{standards,gcc-alignment}'),
  ('SASO 1057', 'saso-1057',
   'Liquefied petroleum gas (LPG) — Specifications and handling',
   'standard', 'in-force', '2017-04-01', '2016-11-12', '2024-02-28',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-1057.aspx',
   'Quality specifications, cylinder labelling, and consumer handling guidance for liquefied petroleum gas distributed in Saudi Arabia.',
   '{standards,energy,worker-safety}'),
  ('SASO 1413', 'saso-1413',
   'Hand-held power tools — Safety requirements',
   'standard', 'in-force', '2018-02-10', '2017-09-30', '2023-11-08',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-1413.aspx',
   'Mandatory safety requirements for hand-held electric and pneumatic power tools — drills, saws, grinders. Covers ergonomics, double-insulation, and emergency stop.',
   '{standards,worker-safety}'),
  ('SASO 2879', 'saso-2879',
   'Domestic gas cooking appliances — Safety',
   'standard', 'in-force', '2019-07-01', '2019-02-22', '2024-03-19',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2879.aspx',
   'Safety requirements for gas-fired domestic cooking appliances using LPG or natural gas. Covers flame failure, thermal stability, surface temperatures.',
   '{standards,worker-safety,energy}'),
  ('SASO 2872', 'saso-2872',
   'Solar photovoltaic modules — Performance and durability',
   'standard', 'in-force', '2020-01-15', '2019-07-25', '2024-06-14',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2872.aspx',
   'Performance and durability standards for crystalline silicon and thin-film PV modules deployed in Saudi Arabia. Mandatory for grid-connected installations under Vision 2030 renewable targets.',
   '{standards,energy,emissions}'),
  ('SASO 2902-3', 'saso-2902-3',
   'Toys safety — Migration of certain elements',
   'standard', 'in-force', '2020-04-01', '2019-12-10', '2024-01-12',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-2902-3.aspx',
   'Maximum migration limits for antimony, arsenic, barium, cadmium, chromium, lead, mercury and selenium in toy materials. Companion to SASO 2902.',
   '{standards,chemicals,worker-safety}'),
  ('SASO IEC 61215', 'saso-iec-61215',
   'Crystalline silicon terrestrial PV modules — Design qualification',
   'standard', 'in-force', '2020-01-15', '2019-08-30', '2024-04-18',
   'https://www.saso.gov.sa/en/Laws-And-Regulations/Technical_regulations/Pages/SASO-IEC-61215.aspx',
   'Saudi adoption of IEC 61215 — design qualification and type approval for crystalline-silicon PV modules. Required for accreditation under SASO 2872.',
   '{standards,energy}')
) as v(citation, slug, title, instrument_type, status,
       effective_date, published_at, last_changed_at, source_url,
       summary, topics)
on conflict (regulator_id, citation) do update
  set title = excluded.title,
      slug = excluded.slug,
      summary = excluded.summary,
      last_changed_at = excluded.last_changed_at,
      source_url = excluded.source_url,
      topics = excluded.topics;
